#include "layer_map.hpp"
#include "render_context.hpp"
#include "ui_overlay.hpp"
#include <cstdlib>
#include <exception>
#include <iostream>
#include <memory>
#include <sdl/command_buffer.hpp>
#include <sdl/copy_pass.hpp>
#include <sdl/device.hpp>
#include <sdl/event.hpp>
#include <sdl/instance.hpp>
#include <sdl/pipeline.hpp>
#include <sdl/render_pass.hpp>
#include <sdl/shader.hpp>
#include <sdl/texture.hpp>
#include <sdl/transfer_buffer.hpp>
#include <sdl/window.hpp>
#include <imgui.h>
#include <imgui_impl_sdl3.h>
#include <imgui_impl_sdlgpu3.h>
#include <SDL3/SDL.h>

// Shader bytecode (generated by shader compilation)
#ifdef __APPLE__
#include <default_metallib.h>
#include <textured_metallib.h>
#else
#include <default_frag_spv.h>
#include <default_vert_spv.h>
#include <textured_frag_spv.h>
#include <textured_vert_spv.h>
#endif

namespace
{
    enum class shader_id
    {
        DEFAULT,
        TEXTURED
    };

    sdl::shader load_shader(const sdl::device& dev, shader_id id, sdl::shader_stage_t stage, uint32_t num_samplers = 0)
    {
#ifdef __APPLE__
        const unsigned char* data = nullptr;
        unsigned int len = 0;

        switch(id)
        {
        case shader_id::DEFAULT:
            data = default_metallib;
            len = default_metallib_len;
            break;
        case shader_id::TEXTURED:
            data = textured_metallib;
            len = textured_metallib_len;
            break;
        }

        const char* entrypoint = (stage == sdl::shader_stage::vertex) ? "vertex_main" : "fragment_main";
        return sdl::shader(dev, data, len, entrypoint, stage, sdl::shader_format::invalid, num_samplers);
#else
        const unsigned char* data = nullptr;
        unsigned int len = 0;

        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                data = default_vert_spv;
                len = default_vert_spv_len;
                break;
            case shader_id::TEXTURED:
                data = textured_vert_spv;
                len = textured_vert_spv_len;
                break;
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                data = default_frag_spv;
                len = default_frag_spv_len;
                break;
            case shader_id::TEXTURED:
                data = textured_frag_spv;
                len = textured_frag_spv_len;
                break;
            }
        }

        const char* entrypoint = (stage == sdl::shader_stage::vertex) ? "vertex_main" : "fragment_main";
        return sdl::shader(dev, data, len, entrypoint, stage, sdl::shader_format::spirv, num_samplers);
#endif
    }
} // anonymous namespace

int main(int argc, char** argv)
{
    if(argc < 3)
    {
        std::cerr << "Usage: nasrbrowse <tile_path> <nasr.db>" << std::endl;
        return EXIT_FAILURE;
    }

    try
    {
        // Initialize SDL
        sdl::instance sdl_ctx;
        auto win_flags = sdl::window_flags_t(
            static_cast<uint64_t>(sdl::window_flags::resizable) |
            static_cast<uint64_t>(sdl::window_flags::high_pixel_density));
        sdl::window win(sdl_ctx, "NASRBrowse", 1280, 800, win_flags);
        sdl::device dev(win, true);

        // Create pipelines
        sdl::pipeline linelist_program(dev,
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::fragment),
            sdl::primitive_type::line_list);

        sdl::pipeline textured_trianglelist_program(dev,
            load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::fragment, 1),
            sdl::primitive_type::triangle_list);

        // Initialize ImGui
        ImGui::CreateContext();
        ImGui::GetIO().IniFilename = nullptr;
        ImGui_ImplSDL3_InitForSDLGPU(win.get());

        ImGui_ImplSDLGPU3_InitInfo imgui_gpu_info = {};
        imgui_gpu_info.Device = dev.get();
        imgui_gpu_info.ColorTargetFormat = SDL_GetGPUSwapchainTextureFormat(dev.get(), win.get());
        ImGui_ImplSDLGPU3_Init(&imgui_gpu_info);

        // Render context
        nasrbrowse::render_context render_ctx(dev);

        // Event manager
        sdl::event_manager event_mgr;
        event_mgr.set_raw_event_hook([](const SDL_Event& event) {
            ImGui_ImplSDL3_ProcessEvent(&event);
        });

        // Create map layer
        auto map_layer = std::make_shared<layer_map>(dev, argv[1], argv[2]);
        event_mgr.add_listener(map_layer);

        // Send initial resize
        map_layer->framebuffer_size_event(1280, 800);

        // UI overlay (FPS display + layer checkboxes)
        nasrbrowse::ui_overlay ui;

        // Main loop
        bool needs_render = true;
        // ImGui auto-resize windows need two frames to stabilize layout
        int imgui_warmup = 2;
        float last_render_ms = 0.0F;
        while(true)
        {
            if(event_mgr.wait_and_dispatch())
            {
                break;
            }

            // Update map state
            needs_render = map_layer->update();

            // Always run ImGui frame so it can process events (hover,
            // click) even when the map hasn't changed
            ImGui_ImplSDLGPU3_NewFrame();
            ImGui_ImplSDL3_NewFrame();
            ImGui::NewFrame();

            if(ui.draw(last_render_ms))
            {
                map_layer->set_visibility(ui.visibility());
                needs_render = true;
            }

            ImGuiIO& io = ImGui::GetIO();
            if(io.WantCaptureMouse)
            {
                needs_render = true;
            }

            if(imgui_warmup > 0)
            {
                imgui_warmup--;
                needs_render = true;
                // Push a dummy event so SDL_WaitEvent returns immediately
                // for the next warmup frame
                if(imgui_warmup > 0)
                {
                    SDL_Event ev = {};
                    ev.type = SDL_EVENT_USER;
                    SDL_PushEvent(&ev);
                }
            }

            ImGui::Render();
            ImDrawData* draw_data = ImGui::GetDrawData();

            if(needs_render)
            {
                uint64_t render_start = SDL_GetPerformanceCounter();
                sdl::command_buffer cmd(dev);

                // Prepare phase
                size_t transfer_size = 0;
                map_layer->prepare(transfer_size);

                if(transfer_size > 0)
                {
                    sdl::transfer_buffer transfer(dev, static_cast<uint32_t>(transfer_size));
                    sdl::copy_pass copy(cmd, transfer);
                    map_layer->copy(copy);
                }

                // Render phase
                unsigned width, height;
                auto swapchain = cmd.acquire_swapchain(win, width, height);
                if(swapchain)
                {
                    // Pass 0: Main scene (clears)
                    {
                        sdl::render_pass pass(cmd, *swapchain, 0.1F, 0.1F, 0.12F, 1.0F);

                        // Textured triangles (tile basemap)
                        pass.bind_pipeline(textured_trianglelist_program);
                        render_ctx.current_pass = nasrbrowse::render_pass_id::textured_trianglelist_0;
                        map_layer->render(pass, render_ctx);

                        // Lines (grid overlay)
                        pass.bind_pipeline(linelist_program);
                        render_ctx.current_pass = nasrbrowse::render_pass_id::trianglelist_0;
                        map_layer->render(pass, render_ctx);
                    }

                    // Pass 1: ImGui overlay (loads existing contents)
                    ImGui_ImplSDLGPU3_PrepareDrawData(draw_data, cmd.get());
                    {
                        SDL_GPUColorTargetInfo color_info = {};
                        color_info.texture = swapchain->get();
                        color_info.load_op = SDL_GPU_LOADOP_LOAD;
                        color_info.store_op = SDL_GPU_STOREOP_STORE;
                        SDL_GPURenderPass* imgui_pass = SDL_BeginGPURenderPass(cmd.get(), &color_info, 1, nullptr);
                        ImGui_ImplSDLGPU3_RenderDrawData(draw_data, cmd.get(), imgui_pass);
                        SDL_EndGPURenderPass(imgui_pass);
                    }
                }

                uint64_t render_end = SDL_GetPerformanceCounter();
                last_render_ms = static_cast<float>(render_end - render_start)
                    / static_cast<float>(SDL_GetPerformanceFrequency()) * 1000.0F;
            }
        }

        // Cleanup ImGui
        ImGui_ImplSDLGPU3_Shutdown();
        ImGui_ImplSDL3_Shutdown();
        ImGui::DestroyContext();

        return EXIT_SUCCESS;
    }
    catch(const std::exception& e)
    {
        std::cerr << "FATAL ERROR: " << e.what() << std::endl;
        return EXIT_FAILURE;
    }
}
