#include "layer_map.hpp"
#include "render_context.hpp"
#include "ui_overlay.hpp"
#include <cstdlib>
#include <exception>
#include <imgui/context.hpp>
#include <iostream>
#include <memory>
#include <sdl/command_buffer.hpp>
#include <sdl/copy_pass.hpp>
#include <sdl/device.hpp>
#include <sdl/event.hpp>
#include <sdl/instance.hpp>
#include <sdl/pipeline.hpp>
#include <sdl/render_pass.hpp>
#include <sdl/shader.hpp>
#include <sdl/texture.hpp>
#include <sdl/timer.hpp>
#include <sdl/window.hpp>

// Shader bytecode (generated by shader compilation)
#ifdef __APPLE__
#include <default_metallib.h>
#include <textured_metallib.h>
#else
#include <default_frag_spv.h>
#include <default_vert_spv.h>
#include <textured_frag_spv.h>
#include <textured_vert_spv.h>
#endif

namespace
{
    enum class shader_id
    {
        DEFAULT,
        TEXTURED
    };

    sdl::shader load_shader(const sdl::device& dev, shader_id id, sdl::shader_stage_t stage, uint32_t num_samplers = 0)
    {
#ifdef __APPLE__
        const unsigned char* data = nullptr;
        unsigned int len = 0;

        switch(id)
        {
        case shader_id::DEFAULT:
            data = default_metallib;
            len = default_metallib_len;
            break;
        case shader_id::TEXTURED:
            data = textured_metallib;
            len = textured_metallib_len;
            break;
        }

        const char* entrypoint = (stage == sdl::shader_stage::vertex) ? "vertex_main" : "fragment_main";
        return sdl::shader(dev, data, len, entrypoint, stage, sdl::shader_format::invalid, num_samplers);
#else
        const unsigned char* data = nullptr;
        unsigned int len = 0;

        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                data = default_vert_spv;
                len = default_vert_spv_len;
                break;
            case shader_id::TEXTURED:
                data = textured_vert_spv;
                len = textured_vert_spv_len;
                break;
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                data = default_frag_spv;
                len = default_frag_spv_len;
                break;
            case shader_id::TEXTURED:
                data = textured_frag_spv;
                len = textured_frag_spv_len;
                break;
            }
        }

        const char* entrypoint = (stage == sdl::shader_stage::vertex) ? "vertex_main" : "fragment_main";
        return sdl::shader(dev, data, len, entrypoint, stage, sdl::shader_format::spirv, num_samplers);
#endif
    }
} // anonymous namespace

int main(int argc, char** argv)
{
    if(argc < 3)
    {
        std::cerr << "Usage: nasrbrowse <tile_path> <nasr.db>" << std::endl;
        return EXIT_FAILURE;
    }

    try
    {
        // Initialize SDL
        sdl::instance sdl_ctx;
        auto win_flags = sdl::window_flags_t(
            static_cast<uint64_t>(sdl::window_flags::resizable) |
            static_cast<uint64_t>(sdl::window_flags::high_pixel_density));
        sdl::window win(sdl_ctx, "NASRBrowse", 1280, 800, win_flags);
        sdl::device dev(win, true);

        // Create pipelines
        sdl::pipeline linelist_program(dev,
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::fragment),
            sdl::primitive_type::line_list);

        sdl::pipeline textured_trianglelist_program(dev,
            load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::fragment, 1),
            sdl::primitive_type::triangle_list);

        // Initialize ImGui
        imgui::context imgui_ctx(dev, win);

        // Render context
        nasrbrowse::render_context render_ctx(dev);

        // Event manager
        sdl::event_manager event_mgr;
        event_mgr.set_raw_event_hook([&imgui_ctx](const SDL_Event& event) {
            imgui_ctx.process_event(&event);
        });

        // Create map layer
        auto map_layer = std::make_shared<layer_map>(dev, argv[1], argv[2]);
        event_mgr.add_listener(map_layer);

        // Send initial resize
        map_layer->framebuffer_size_event(1280, 800);

        // UI overlay (FPS display + layer checkboxes)
        nasrbrowse::ui_overlay ui;

        // Main loop
        bool needs_render = true;
        float last_render_ms = 0.0F;
        while(true)
        {
            if(event_mgr.wait_and_dispatch())
            {
                break;
            }

            // Update map state
            needs_render = map_layer->update();

            // Always run ImGui frame so it can process events (hover,
            // click) even when the map hasn't changed
            imgui_ctx.new_frame();

            if(ui.draw(last_render_ms))
            {
                map_layer->set_visibility(ui.visibility());
                needs_render = true;
            }

            if(imgui_ctx.wants_mouse())
            {
                needs_render = true;
            }

            if(imgui_ctx.warming_up())
            {
                needs_render = true;
            }

            imgui_ctx.end_frame();

            if(needs_render)
            {
                sdl::timer render_timer;
                sdl::command_buffer cmd(dev);

                // Copy phase: upload pending data to GPU
                {
                    sdl::copy_pass copy(cmd);
                    map_layer->copy(copy);
                }

                // Render phase
                unsigned width, height;
                auto swapchain = cmd.acquire_swapchain(win, width, height);
                if(swapchain)
                {
                    // Pass 0: Main scene (clears)
                    {
                        sdl::render_pass pass(cmd, *swapchain, 0.1F, 0.1F, 0.12F, 1.0F);

                        // Textured triangles (tile basemap)
                        pass.bind_pipeline(textured_trianglelist_program);
                        render_ctx.current_pass = nasrbrowse::render_pass_id::textured_trianglelist_0;
                        map_layer->render(pass, render_ctx);

                        // Lines (grid overlay)
                        pass.bind_pipeline(linelist_program);
                        render_ctx.current_pass = nasrbrowse::render_pass_id::trianglelist_0;
                        map_layer->render(pass, render_ctx);
                    }

                    // Pass 1: ImGui overlay
                    imgui_ctx.render(cmd, *swapchain);
                }

                last_render_ms = render_timer.elapsed_ms();
            }
        }

        return EXIT_SUCCESS;
    }
    catch(const std::exception& e)
    {
        std::cerr << "FATAL ERROR: " << e.what() << std::endl;
        return EXIT_FAILURE;
    }
}
