#include "map_widget.hpp"
#include "feature_type.hpp"
#include "feature_renderer.hpp"
#include "geo_math.hpp"
#include "label_renderer.hpp"
#include "map_view.hpp"
#include "nasr_database.hpp"
#include "pick_result.hpp"
#include "render_context.hpp"
#include "tile_renderer.hpp"
#include "ui_overlay.hpp"
#include "ui_sectioned_list.hpp"
#include "chart_style.hpp"
#include <algorithm>
#include <memory>
#include <string>
#include <glm/ext/matrix_clip_space.hpp>
#include <glm/ext/matrix_projection.hpp>
#include <glm/ext/matrix_transform.hpp>
#include <unordered_set>
#include <imgui.h>
#include <iostream>
#include <sdl/buffer.hpp>
#include <sdl/command_buffer.hpp>
#include <sdl/copy_pass.hpp>
#include <sdl/device.hpp>
#include <sdl/font.hpp>
#include <sdl/pipeline.hpp>
#include <sdl/render_pass.hpp>
#include <sdl/sampler.hpp>
#include <sdl/shader.hpp>
#include <sdl/text_engine.hpp>
#include <sdl/types.hpp>
#include <sstream>
#include <string>
#include <vector>

// Shader bytecode (generated by shader compilation)
#ifdef __APPLE__
#include <default_metallib.h>
#include <line_metallib.h>
#include <textured_metallib.h>
#endif
#include <default_frag_spv.h>
#include <default_vert_spv.h>
#include <line_frag_spv.h>
#include <line_vert_spv.h>
#include <textured_frag_spv.h>
#include <textured_vert_spv.h>
#ifdef _WIN32
#include <default_frag_dxil.h>
#include <default_vert_dxil.h>
#include <line_frag_dxil.h>
#include <line_vert_dxil.h>
#include <textured_frag_dxil.h>
#include <textured_vert_dxil.h>
#endif

// Embedded font
#include <NotoSans_Regular_ttf.h>

namespace
{
    enum class shader_id { DEFAULT, LINE, TEXTURED };

    struct shader_bytecode { const unsigned char* data; unsigned int len; };

    shader_bytecode get_spirv_bytecode(shader_id id, sdl::shader_stage_t stage)
    {
        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:  return { default_vert_spv, default_vert_spv_len };
            case shader_id::LINE:     return { line_vert_spv, line_vert_spv_len };
            case shader_id::TEXTURED: return { textured_vert_spv, textured_vert_spv_len };
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:  return { default_frag_spv, default_frag_spv_len };
            case shader_id::LINE:     return { line_frag_spv, line_frag_spv_len };
            case shader_id::TEXTURED: return { textured_frag_spv, textured_frag_spv_len };
            }
        }
        return { nullptr, 0 };
    }

#ifdef _WIN32
    shader_bytecode get_dxil_bytecode(shader_id id, sdl::shader_stage_t stage)
    {
        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:  return { default_vert_dxil, default_vert_dxil_len };
            case shader_id::LINE:     return { line_vert_dxil, line_vert_dxil_len };
            case shader_id::TEXTURED: return { textured_vert_dxil, textured_vert_dxil_len };
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:  return { default_frag_dxil, default_frag_dxil_len };
            case shader_id::LINE:     return { line_frag_dxil, line_frag_dxil_len };
            case shader_id::TEXTURED: return { textured_frag_dxil, textured_frag_dxil_len };
            }
        }
        return { nullptr, 0 };
    }
#endif

#ifdef __APPLE__
    shader_bytecode get_metallib_bytecode(shader_id id)
    {
        switch(id)
        {
        case shader_id::DEFAULT:  return { default_metallib, default_metallib_len };
        case shader_id::LINE:     return { line_metallib, line_metallib_len };
        case shader_id::TEXTURED: return { textured_metallib, textured_metallib_len };
        }
        return { nullptr, 0 };
    }
#endif

    sdl::shader load_shader(const sdl::device& dev, shader_id id, sdl::shader_stage_t stage,
                            uint32_t num_samplers = 0, uint32_t num_storage_buffers = 0)
    {
        const auto* entrypoint = (stage == sdl::shader_stage::vertex) ? "vertex_main" : "fragment_main";
        auto format = dev.get_shader_format();
        shader_bytecode bc = { nullptr, 0 };
#ifdef __APPLE__
        if(format == sdl::shader_format::metallib)
        {
            bc = get_metallib_bytecode(id);
            return sdl::shader(dev, bc.data, bc.len, entrypoint, stage, format, num_samplers, num_storage_buffers);
        }
#endif
#ifdef _WIN32
        if(format == sdl::shader_format::dxil)
            bc = get_dxil_bytecode(id, stage);
        else
#endif
            bc = get_spirv_bytecode(id, stage);
        return sdl::shader(dev, bc.data, bc.len, entrypoint, stage, format, num_samplers, num_storage_buffers);
    }
}

// Pick box size in pixels (width and height of the pick region for point features)
constexpr int PICK_BOX_SIZE_PIXELS = 20;

// Exact-point short-circuit radius: a single point feature this close to the
// cursor skips the candidate-selector popup and logs directly.
constexpr int PICK_BOX_EXACT_SIZE_PIXELS = 4;

// Padding between the click anchor and the selector popup, in pixels.
constexpr float PICK_POPUP_ANCHOR_PADDING = 12.0F;

// SDL left mouse button value
constexpr uint8_t BUTTON_LEFT = 1;

namespace
{
    // Selector-popup state. Lives in map_widget::impl.
    struct pick_popup_state
    {
        bool open = false;
        int session_id = 0;
        // ImGui window ID — refreshed from session_id on each open so ImGui
        // treats every session as a new window (no stale size/position).
        std::string window_id;
        int warmup_frames = 0;  // ImGui hides a freshly-created auto-resize
                                // window for its first frame while it measures
                                // content. Force a couple of extra renders so
                                // the popup actually appears without needing a
                                // subsequent mouse event to wake the main loop.
        double click_lon = 0.0;
        double click_lat = 0.0;
        std::vector<nasrbrowse::feature> features;
        bool route_hit = false;
    };

    // Info-popup state: details for a single selected feature.
    struct info_popup_state
    {
        bool open = false;
        int session_id = 0;
        std::string window_id;     // see pick_popup_state::window_id
        int warmup_frames = 0;
        double anchor_lon = 0.0;
        double anchor_lat = 0.0;
        nasrbrowse::feature feature{nasrbrowse::airport{}};
    };
}

struct map_widget::impl
{
    nasrbrowse::map_view view;
    sdl::device& dev;
    bool needs_update;
    bool show_tiles;

    // GPU pipelines (created once at construction)
    sdl::pipeline linelist_pipeline;
    sdl::pipeline trianglelist_pipeline;
    sdl::pipeline textured_pipeline;
    sdl::pipeline line_sdf_pipeline;

    // Tile renderer for raster basemap (null if no basemap was provided)
    std::unique_ptr<nasrbrowse::tile_renderer> tiles;

    // Vector feature renderer
    nasrbrowse::feature_renderer features;

    // Grid line vertex buffer (rebuilt on viewport change)
    std::vector<sdl::vertex_t2f_c4ub_v3f> grid_vertices;
    std::unique_ptr<sdl::buffer> grid_buffer;

    // Text rendering (owned; only label_renderer uses these)
    sdl::text_engine text_engine;
    sdl::font label_font;
    sdl::font outline_font;
    sdl::sampler text_sampler;

    // Label renderer
    nasrbrowse::label_renderer labels;

    // Render context (projection, sampler, pass ID)
    nasrbrowse::render_context render_ctx;

    // NASR database for picks and search
    nasrbrowse::nasr_database pick_db;
    nasrbrowse::chart_style styles;
    nasrbrowse::layer_visibility vis;
    double cursor_ndc_x;
    double cursor_ndc_y;
    bool dragged;
    bool imgui_wants_mouse;
    bool imgui_wants_keyboard;

    pick_popup_state pick_popup;
    info_popup_state info_popup;

    std::vector<std::unique_ptr<nasrbrowse::feature_type>> feature_types;

    std::optional<nasrbrowse::flight_route> route;
    bool route_selected = false;
    bool route_dirty = false;

    // Route drag state. Waypoint hit takes priority over segment hit so
    // dragging an existing waypoint doesn't get mistaken for an insert.
    enum class route_drag_mode { none, segment, waypoint };
    struct {
        route_drag_mode mode = route_drag_mode::none;
        int index = 0;  // segment index (segment mode) or wp index (waypoint mode)
    } route_drag;

    // Event dispatch state
    glm::mat4 projection_matrix{1.0F};
    float normalized_viewport_width = 1.0F;
    glm::vec4 viewport_vec{0.0F};
    std::unordered_set<sdl::input_button_t> buttons_down;
    double cursor_last_x = 0;
    double cursor_last_y = 0;

    impl(sdl::device& dev, const char* tile_path,
         const char* db_path, const char* conf_path)
        : dev(dev)
        , needs_update(true)
        , show_tiles(true)
        , linelist_pipeline(dev,
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::fragment),
            sdl::primitive_type::line_list)
        , trianglelist_pipeline(dev,
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::fragment),
            sdl::primitive_type::triangle_list)
        , textured_pipeline(dev,
            load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::vertex),
            load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::fragment, 1),
            sdl::primitive_type::triangle_list)
        , line_sdf_pipeline(dev,
            load_shader(dev, shader_id::LINE, sdl::shader_stage::vertex, 0, 2),
            load_shader(dev, shader_id::LINE, sdl::shader_stage::fragment, 0, 2),
            sdl::primitive_type::triangle_list,
            sdl::texture_format_t(0), false)
        , tiles(tile_path
              ? std::make_unique<nasrbrowse::tile_renderer>(dev, tile_path)
              : nullptr)
        , features(dev, db_path, nasrbrowse::chart_style(conf_path, nasrbrowse::chart_mode::vfr))
        , text_engine(dev)
        , label_font(text_engine, NotoSans_Regular_ttf, NotoSans_Regular_ttf_len, 13)
        , outline_font(text_engine, NotoSans_Regular_ttf, NotoSans_Regular_ttf_len, 13)
        , text_sampler(dev, sdl::filter::nearest, sdl::filter::nearest,
                       sdl::sampler_address_mode::clamp_to_edge)
        , labels(dev, text_engine, label_font, outline_font)
        , render_ctx(dev)
        , pick_db(db_path)
        , styles(conf_path, nasrbrowse::chart_mode::vfr)
        , cursor_ndc_x(0)
        , cursor_ndc_y(0)
        , dragged(false)
        , imgui_wants_mouse(false)
        , imgui_wants_keyboard(false)
        , feature_types(nasrbrowse::make_feature_types())
    {
        outline_font.set_outline(1);
    }

    void rebuild_grid()
    {
        grid_vertices.clear();

        auto vx_min = view.view_x_min();
        auto vx_max = view.view_x_max();
        auto vy_min = view.view_y_min();
        auto vy_max = view.view_y_max();
        auto range_x = vx_max - vx_min;
        auto range_y = vy_max - vy_min;

        // Normalize coordinates to -0.5..0.5 for rendering
        auto to_ndc_x = [&](double mx) -> float
        {
            return static_cast<float>((mx - vx_min) / range_x - 0.5) * view.aspect_ratio();
        };
        auto to_ndc_y = [&](double my) -> float
        {
            return static_cast<float>((my - vy_min) / range_y - 0.5);
        };

        // Draw grid lines at regular lat/lon intervals
        // Choose interval based on zoom level
        auto approx_zoom = view.zoom_level();
        double lon_step;
        double lat_step;
        if(approx_zoom < 3)
        {
            lon_step = 30.0;
            lat_step = 30.0;
        }
        else if(approx_zoom < 5)
        {
            lon_step = 10.0;
            lat_step = 10.0;
        }
        else if(approx_zoom < 7)
        {
            lon_step = 5.0;
            lat_step = 5.0;
        }
        else if(approx_zoom < 9)
        {
            lon_step = 1.0;
            lat_step = 1.0;
        }
        else
        {
            lon_step = 0.5;
            lat_step = 0.5;
        }

        // Grid line color: dark gray, semi-transparent
        uint8_t r = 80;
        uint8_t g = 80;
        uint8_t b = 80;
        uint8_t a = 160;

        // Longitude lines (vertical)
        auto lon_min = nasrbrowse::mx_to_lon(vx_min);
        auto lon_max = nasrbrowse::mx_to_lon(vx_max);
        auto lon_start = std::floor(lon_min / lon_step) * lon_step;
        for(double lon = lon_start; lon <= lon_max; lon += lon_step)
        {
            auto mx = nasrbrowse::lon_to_mx(lon);
            auto nx = to_ndc_x(mx);
            auto ny0 = to_ndc_y(vy_min);
            auto ny1 = to_ndc_y(vy_max);
            grid_vertices.push_back({ 0, 0, r, g, b, a, nx, ny0, 0 });
            grid_vertices.push_back({ 0, 0, r, g, b, a, nx, ny1, 0 });
        }

        // Latitude lines (horizontal, non-uniform spacing in Mercator)
        auto lat_min = nasrbrowse::my_to_lat(vy_min);
        auto lat_max = nasrbrowse::my_to_lat(vy_max);
        auto lat_start = std::floor(lat_min / lat_step) * lat_step;
        for(double lat = lat_start; lat <= lat_max; lat += lat_step)
        {
            auto my = nasrbrowse::lat_to_my(lat);
            auto ny = to_ndc_y(my);
            auto nx0 = to_ndc_x(vx_min);
            auto nx1 = to_ndc_x(vx_max);
            grid_vertices.push_back({ 0, 0, r, g, b, a, nx0, ny, 0 });
            grid_vertices.push_back({ 0, 0, r, g, b, a, nx1, ny, 0 });
        }

        needs_update = true;
    }

    void update_tiles()
    {
        if(tiles)
        {
            tiles->update(view.view_x_min(), view.view_y_min(),
                          view.view_x_max(), view.view_y_max(),
                          view.half_extent_y, view.viewport_height,
                          view.aspect_ratio());
        }
        features.update(view.view_x_min(), view.view_y_min(),
                        view.view_x_max(), view.view_y_max(),
                        view.half_extent_y, view.viewport_height,
                        view.aspect_ratio());
    }

    nasrbrowse::pick_result pick_at(double ndc_x, double ndc_y)
    {
        using namespace nasrbrowse;

        // NDC → Web Mercator → lon/lat, wrapping lon to [-180, 180] for DB.
        auto world_x = ndc_x * 2.0 * view.half_extent_y + view.center_x;
        auto world_y = ndc_y * 2.0 * view.half_extent_y + view.center_y;
        auto click_lon = mx_to_lon(world_x);
        auto click_lat = my_to_lat(world_y);
        click_lon = std::fmod(click_lon + 180.0, 360.0);
        if(click_lon < 0) click_lon += 360.0;
        click_lon -= 180.0;

        // Point-feature pick box: pixel half-size → world coords.
        auto pick_half_ndc = (PICK_BOX_SIZE_PIXELS * 0.5) / view.viewport_height;
        auto box_world_half = pick_half_ndc * 2.0 * view.half_extent_y;
        auto box_lon_half = mx_to_lon(box_world_half);
        geo_bbox pick_box{
            click_lon - box_lon_half,
            my_to_lat(world_y - box_world_half),
            click_lon + box_lon_half,
            my_to_lat(world_y + box_world_half)};
        geo_bbox click_box{click_lon, click_lat, click_lon, click_lat};

        nasrbrowse::pick_context ctx{
            pick_db, styles, vis,
            view.zoom_level(),
            click_lon, click_lat,
            pick_box, click_box,
            (pick_box.lat_max - pick_box.lat_min) * 0.5 * 60.0};

        pick_result result;
        result.lon = click_lon;
        result.lat = click_lat;
        for(const auto& obj : feature_types)
            if(vis[obj->layer_id()])
                obj->pick(ctx, result.features);
        return result;
    }

    // NDC → world lon/lat (same math pick_at uses to derive click_lon/lat,
    // without running the feature-type pick pass).
    std::pair<double, double> ndc_to_lonlat(double ndc_x, double ndc_y) const
    {
        auto world_x = ndc_x * 2.0 * view.half_extent_y + view.center_x;
        auto world_y = ndc_y * 2.0 * view.half_extent_y + view.center_y;
        auto lon = nasrbrowse::mx_to_lon(world_x);
        auto lat = nasrbrowse::my_to_lat(world_y);
        lon = std::fmod(lon + 180.0, 360.0);
        if(lon < 0) lon += 360.0;
        lon -= 180.0;
        return {lon, lat};
    }

    // Distance from point (px, py) to the segment (ax, ay)-(bx, by).
    static float point_segment_distance_px(float px, float py,
                                            float ax, float ay,
                                            float bx, float by)
    {
        auto dx = bx - ax;
        auto dy = by - ay;
        auto len_sq = dx * dx + dy * dy;
        auto t = 0.0F;
        if(len_sq > 0) t = ((px - ax) * dx + (py - ay) * dy) / len_sq;
        t = std::clamp(t, 0.0F, 1.0F);
        auto cx = ax + t * dx;
        auto cy = ay + t * dy;
        return std::sqrt((px - cx) * (px - cx) + (py - cy) * (py - cy));
    }

    // Return the 0-based waypoint index whose pixel position is within
    // pick distance of the click, or nullopt.
    std::optional<int> hit_route_waypoint(double click_lon, double click_lat) const
    {
        if(!route) return std::nullopt;
        float cursor_px;
        float cursor_py;
        view.world_to_pixel(click_lon, click_lat, cursor_px, cursor_py);
        const auto threshold = PICK_BOX_SIZE_PIXELS * 0.5F;
        const auto& wps = route->waypoints;
        for(std::size_t i = 0; i < wps.size(); ++i)
        {
            float wx;
            float wy;
            view.world_to_pixel(
                nasrbrowse::waypoint_lon(wps[i]),
                nasrbrowse::waypoint_lat(wps[i]), wx, wy);
            auto dx = wx - cursor_px;
            auto dy = wy - cursor_py;
            if(dx * dx + dy * dy < threshold * threshold)
                return static_cast<int>(i);
        }
        return std::nullopt;
    }

    // Return the 0-based leg index whose great-circle polyline the click
    // lands on, or nullopt if no route leg is within pick distance.
    std::optional<int> hit_route_segment(double click_lon, double click_lat) const
    {
        if(!route || route->waypoints.size() < 2) return std::nullopt;

        float cursor_px;
        float cursor_py;
        view.world_to_pixel(click_lon, click_lat, cursor_px, cursor_py);
        const auto threshold = PICK_BOX_SIZE_PIXELS * 0.5F;

        const auto& wps = route->waypoints;
        for(std::size_t i = 1; i < wps.size(); ++i)
        {
            auto arc = nasrbrowse::geodesic_interpolate(
                nasrbrowse::waypoint_lat(wps[i - 1]),
                nasrbrowse::waypoint_lon(wps[i - 1]),
                nasrbrowse::waypoint_lat(wps[i]),
                nasrbrowse::waypoint_lon(wps[i]));
            for(std::size_t j = 1; j < arc.size(); ++j)
            {
                float ax;
                float ay;
                float bx;
                float by;
                view.world_to_pixel(arc[j - 1].lon, arc[j - 1].lat, ax, ay);
                view.world_to_pixel(arc[j].lon, arc[j].lat, bx, by);
                if(point_segment_distance_px(
                    cursor_px, cursor_py, ax, ay, bx, by) < threshold)
                    return static_cast<int>(i - 1);
            }
        }
        return std::nullopt;
    }

    // Resolve a release point to a route_waypoint: prefer the first
    // airport/navaid/fix under the cursor; otherwise lat/lon at the click.
    nasrbrowse::route_waypoint resolve_release_waypoint()
    {
        auto pick = pick_at(cursor_ndc_x, cursor_ndc_y);
        for(const auto& f : pick.features)
        {
            if(std::holds_alternative<nasrbrowse::airport>(f))
            {
                const auto& a = std::get<nasrbrowse::airport>(f);
                return nasrbrowse::airport_ref{a.arpt_id, a};
            }
            if(std::holds_alternative<nasrbrowse::navaid>(f))
            {
                const auto& n = std::get<nasrbrowse::navaid>(f);
                return nasrbrowse::navaid_ref{n.nav_id, n};
            }
            if(std::holds_alternative<nasrbrowse::fix>(f))
            {
                const auto& x = std::get<nasrbrowse::fix>(f);
                return nasrbrowse::fix_ref{x.fix_id, x};
            }
        }
        return nasrbrowse::route_waypoint{
            nasrbrowse::latlon_ref{pick.lat, pick.lon}};
    }

    void notify_route_changed()
    {
        features.set_route(route);
        route_dirty = true;
        needs_update = true;
        update_tiles();
    }

    void handle_route_drag_release(route_drag_mode mode)
    {
        if(!route) return;
        if(mode == route_drag_mode::segment)
        {
            route->insert_waypoint(route_drag.index, resolve_release_waypoint());
            notify_route_changed();
            return;
        }

        // Waypoint mode. If release lands on an adjacent waypoint, delete
        // the dragged waypoint (but only if the route keeps >= 2
        // waypoints afterward). Otherwise replace it with whatever's
        // under the cursor.
        int i = route_drag.index;
        auto [lon, lat] = ndc_to_lonlat(cursor_ndc_x, cursor_ndc_y);
        auto hit = hit_route_waypoint(lon, lat);
        auto adjacent = hit && (*hit == i - 1 || *hit == i + 1);

        if(adjacent && route->waypoints.size() > 2)
        {
            route->delete_waypoint(i);
        }
        else
        {
            route->replace_waypoint(i, resolve_release_waypoint());
        }
        notify_route_changed();
    }

    void set_route_selected(bool selected)
    {
        if(route_selected == selected) return;
        route_selected = selected;
        features.set_route_selected(selected);
        needs_update = true;
        update_tiles();
    }

    // Convert a world lon/lat into pixel coordinates relative to the
    // Compute where to place a popup anchored at world coord (lon, lat).
    // Returns true and fills pos/pivot when the anchor is on-screen.
    // Returns false when off-screen (popup should dismiss).
    bool compute_popup_anchor(double lon, double lat,
                              ImVec2& pos, ImVec2& pivot) const
    {
        float ax;
        float ay;
        view.world_to_pixel(lon, lat, ax, ay);
        if(ax < 0 || ax > view.viewport_width || ay < 0 || ay > view.viewport_height)
            return false;

        auto right  = ax >= view.viewport_width * 0.5F;
        auto bottom = ay >= view.viewport_height * 0.5F;

        pos.x = ax + (right  ? -PICK_POPUP_ANCHOR_PADDING : PICK_POPUP_ANCHOR_PADDING);
        pos.y = ay + (bottom ? -PICK_POPUP_ANCHOR_PADDING : PICK_POPUP_ANCHOR_PADDING);
        pivot = ImVec2(right ? 1.0F : 0.0F, bottom ? 1.0F : 0.0F);
        return true;
    }

    // Open (or replace) the info popup showing details for a selected feature.
    void open_info_popup(const nasrbrowse::feature& f,
                          double click_lon, double click_lat)
    {
        auto [alon, alat] = nasrbrowse::find_feature_type(feature_types, f)
                              .anchor_lonlat(f, click_lon, click_lat);
        info_popup.open = true;
        ++info_popup.session_id;
        info_popup.window_id = "##info_popup_" + std::to_string(info_popup.session_id);
        info_popup.warmup_frames = 2;
        info_popup.anchor_lon = alon;
        info_popup.anchor_lat = alat;
        info_popup.feature = f;
        features.set_selection(f);
        set_route_selected(false);
        update_tiles();
        needs_update = true;
    }

    void close_info_popup()
    {
        info_popup.open = false;
        features.set_selection(std::nullopt);
        update_tiles();
        needs_update = true;
    }

    // Handle a completed left-click pick: run pick_at, apply exact-point
    // short-circuit, and either open the info popup directly or open
    // the selector popup.
    void handle_pick()
    {
        pick_popup.open = false;
        pick_popup.features.clear();
        pick_popup.route_hit = false;

        auto result = pick_at(cursor_ndc_x, cursor_ndc_y);

        auto route_hit = route && hit_route_segment(result.lon, result.lat).has_value();

        // Route-only click (no other features): select directly without popup.
        if(result.features.empty() && route_hit)
        {
            close_info_popup();
            set_route_selected(true);
            return;
        }

        // Exact-point short-circuit: count point features within the
        // exact-pick pixel radius of the click.
        const double exact_threshold_px = PICK_BOX_EXACT_SIZE_PIXELS;
        auto exact_count = 0;
        const nasrbrowse::feature* exact_hit = nullptr;
        for(const auto& f : result.features)
        {
            auto coord = nasrbrowse::find_feature_type(feature_types, f).point_coord(f);
            if(!coord) continue;
            float fx;
            float fy;
            view.world_to_pixel(coord->first, coord->second, fx, fy);
            float cx;
            float cy;
            view.world_to_pixel(result.lon, result.lat, cx, cy);
            double dx = fx - cx;
            double dy = fy - cy;
            if(std::sqrt(dx * dx + dy * dy) <= exact_threshold_px)
            {
                ++exact_count;
                exact_hit = &f;
            }
        }

        if(exact_count == 1)
        {
            open_info_popup(*exact_hit, result.lon, result.lat);
            return;
        }

        // Opening the selector supersedes any stale info popup.
        close_info_popup();
        pick_popup.open = true;
        ++pick_popup.session_id;
        pick_popup.window_id = "##pick_selector_" + std::to_string(pick_popup.session_id);
        pick_popup.warmup_frames = 2;
        pick_popup.click_lon = result.lon;
        pick_popup.click_lat = result.lat;
        pick_popup.features = std::move(result.features);
        pick_popup.route_hit = route_hit;
        needs_update = true;
    }

    // Draw the selector popup during an ImGui frame. Called from the main
    // loop between new_frame and end_frame. Also auto-dismisses if the
    // anchor point has scrolled out of the viewport.
    // Returns true if another render frame is needed.
    bool draw_pick_imgui()
    {
        if(!pick_popup.open) return false;

        ImVec2 pos, pivot;
        if(!compute_popup_anchor(pick_popup.click_lon, pick_popup.click_lat, pos, pivot))
        {
            pick_popup.open = false;
            return false;
        }

        ImGui::SetNextWindowPos(pos, ImGuiCond_Always, pivot);
        ImGui::SetNextWindowBgAlpha(0.9F);
        ImGui::SetNextWindowSizeConstraints(ImVec2(220, 0), ImVec2(FLT_MAX, view.viewport_height * 0.8F));
        ImGui::Begin(pick_popup.window_id.c_str(), nullptr,
            ImGuiWindowFlags_NoCollapse |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_AlwaysAutoResize |
            ImGuiWindowFlags_NoTitleBar);

        // Header row: lat/long on the left, [X] on the right
        ImGui::Text("Lat, Long: %.5f, %.5f", pick_popup.click_lat, pick_popup.click_lon);
        ImGui::SameLine();
        // Align close button to right edge of the window content region
        auto btn_w = ImGui::GetFrameHeight();
        auto avail = ImGui::GetContentRegionAvail().x;
        if(avail > btn_w)
            ImGui::SetCursorPosX(ImGui::GetCursorPosX() + avail - btn_w);
        if(ImGui::SmallButton("X##pick_close"))
        {
            pick_popup.open = false;
            ImGui::End();
            return false;
        }

        if(!pick_popup.features.empty() || pick_popup.route_hit)
        {
            ImGui::Separator();

            // Group pick features by their canonical feature-section tag,
            // then append a synthetic "ROUTE" section when the route was hit.
            const auto route_section = nasrbrowse::FEATURE_SECTION_COUNT;
            std::vector<nasrbrowse::ui_section> sections(route_section + 1);
            std::vector<std::vector<int>> section_feature_index(route_section + 1);
            for(std::size_t s = 0; s < nasrbrowse::FEATURE_SECTION_COUNT; ++s)
                sections[s].header = nasrbrowse::FEATURE_SECTIONS[s].header;
            sections[route_section].header = "ROUTE";

            for(int i = 0; i < static_cast<int>(pick_popup.features.size()); ++i)
            {
                const auto& f = pick_popup.features[i];
                const auto& t = nasrbrowse::find_feature_type(feature_types, f);
                auto s = nasrbrowse::feature_section_index(t.section_tag());
                if(s < 0) continue;
                sections[s].items.push_back(t.summary(f));
                section_feature_index[s].push_back(i);
            }

            if(pick_popup.route_hit)
                sections[route_section].items.emplace_back("Flight route");

            auto picked = nasrbrowse::draw_sectioned_selectable_list(sections);
            if(picked)
            {
                if(static_cast<std::size_t>(picked->first) == route_section)
                {
                    close_info_popup();
                    set_route_selected(true);
                }
                else
                {
                    auto fi = section_feature_index[picked->first][picked->second];
                    open_info_popup(pick_popup.features[fi],
                                    pick_popup.click_lon, pick_popup.click_lat);
                }
                pick_popup.open = false;
                pick_popup.features.clear();
                pick_popup.route_hit = false;
            }
        }

        ImGui::End();

        auto need_more = pick_popup.warmup_frames > 0;
        if(need_more) --pick_popup.warmup_frames;
        return need_more;
    }

    // Max width of the value column (in pixels); anything longer wraps.
    static constexpr float INFO_VALUE_WRAP_PX = 280.0F;

    // Draw the info popup for the currently selected feature. Returns true
    // while warming up (first measurement frame).
    bool draw_info_imgui()
    {
        if(!info_popup.open) return false;

        ImVec2 pos, pivot;
        if(!compute_popup_anchor(info_popup.anchor_lon, info_popup.anchor_lat, pos, pivot))
        {
            close_info_popup();
            return false;
        }

        ImGui::SetNextWindowPos(pos, ImGuiCond_Always, pivot);
        ImGui::SetNextWindowBgAlpha(0.9F);
        ImGui::SetNextWindowSizeConstraints(ImVec2(220, 0), ImVec2(FLT_MAX, view.viewport_height * 0.9F));
        ImGui::Begin(info_popup.window_id.c_str(), nullptr,
            ImGuiWindowFlags_NoCollapse |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_AlwaysAutoResize |
            ImGuiWindowFlags_NoTitleBar);

        // Title row: feature summary on the left, [X] on the right.
        const auto& L = nasrbrowse::find_feature_type(feature_types, info_popup.feature);
        auto title = L.summary(info_popup.feature);
        ImGui::TextUnformatted(title.c_str());
        ImGui::SameLine();
        auto btn_w = ImGui::GetFrameHeight();
        auto avail = ImGui::GetContentRegionAvail().x;
        if(avail > btn_w)
            ImGui::SetCursorPosX(ImGui::GetCursorPosX() + avail - btn_w);
        if(ImGui::SmallButton("X##info_close"))
        {
            close_info_popup();
            ImGui::End();
            return false;
        }
        ImGui::Separator();

        // Two-column layout: fixed-width keys (auto-fit) + fixed-width
        // wrapped values. Using an ImGui table gives us per-cell wrapping
        // while keeping the key column aligned.
        auto rows = L.info_kv(info_popup.feature);
        const ImGuiTableFlags flags =
            ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_NoHostExtendX;
        if(ImGui::BeginTable("info_kv", 2, flags))
        {
            ImGui::TableSetupColumn("k", ImGuiTableColumnFlags_WidthFixed);
            ImGui::TableSetupColumn("v", ImGuiTableColumnFlags_WidthFixed, INFO_VALUE_WRAP_PX);

            auto line_h = ImGui::GetTextLineHeight();
            for(const auto& [key, value] : rows)
            {
                if(value.empty()) continue;  // hide empty-source fields
                ImGui::TableNextRow();

                // Measure the wrapped value so we can vertically center
                // the key against it when the value spans multiple lines.
                auto val_size = ImGui::CalcTextSize(
                    value.c_str(), nullptr, false, INFO_VALUE_WRAP_PX);
                auto row_h = val_size.y > line_h ? val_size.y : line_h;

                ImGui::TableSetColumnIndex(0);
                auto y_offset = (row_h - line_h) * 0.5F;
                if(y_offset > 0.0F)
                    ImGui::SetCursorPosY(ImGui::GetCursorPosY() + y_offset);
                ImGui::TextUnformatted(key);

                ImGui::TableSetColumnIndex(1);
                ImGui::PushTextWrapPos(ImGui::GetCursorPosX() + INFO_VALUE_WRAP_PX);
                // Right-justify the value: push its starting X so the
                // rendered (wrapped) block ends at the column's right edge.
                auto val_w = val_size.x;
                if(val_w < INFO_VALUE_WRAP_PX)
                    ImGui::SetCursorPosX(ImGui::GetCursorPosX() + (INFO_VALUE_WRAP_PX - val_w));
                ImGui::TextUnformatted(value.c_str());
                ImGui::PopTextWrapPos();
            }
            ImGui::EndTable();
        }

        ImGui::End();

        auto need_more = info_popup.warmup_frames > 0;
        if(need_more) --info_popup.warmup_frames;
        return need_more;
    }
};

map_widget::map_widget(sdl::device& dev, const char* tile_path,
                       const char* db_path, const char* conf_path)
    : pimpl(std::make_unique<impl>(dev, tile_path, db_path, conf_path))
{
}

map_widget::~map_widget() = default;

void map_widget::set_visibility(const nasrbrowse::layer_visibility& vis)
{
    pimpl->show_tiles = vis[nasrbrowse::layer_basemap];
    pimpl->vis = vis;
    pimpl->features.set_visibility(vis);
    pimpl->needs_update = true;
    // Kick a requery in case the altitude filter invalidated the cache —
    // otherwise nothing re-runs until the next input event.
    pimpl->update_tiles();
}

void map_widget::focus_on_hit(const nasrbrowse::search_hit& hit)
{
    auto bbox = pimpl->pick_db.get_hit_bbox(hit);
    if(!bbox) return;

    auto& d = *pimpl;
    auto cx = (bbox->lon_min + bbox->lon_max) * 0.5;
    auto cy = (bbox->lat_min + bbox->lat_max) * 0.5;
    d.view.center_x = nasrbrowse::lon_to_mx(cx);
    d.view.center_y = nasrbrowse::lat_to_my(cy);

    // Degenerate bbox (point entity) → use a fixed close-in zoom level so
    // the feature is guaranteed visible under chart_style's per-type
    // min_zoom thresholds (navaids appear by ~z9, airports by ~z7, fixes
    // by ~z10 — zoom 12 covers all of them comfortably).
    constexpr int POINT_FOCUS_ZOOM = 12;
    auto is_point = (bbox->lon_min == bbox->lon_max &&
                     bbox->lat_min == bbox->lat_max);
    if(is_point)
    {
        d.view.zoom_to_level(POINT_FOCUS_ZOOM);
    }
    else
    {
        // Fit the bbox with 20% padding. Use the larger of the required
        // vertical / horizontal extents (the latter scaled by aspect ratio).
        auto half_height_m =
            (nasrbrowse::lat_to_my(bbox->lat_max) -
             nasrbrowse::lat_to_my(bbox->lat_min)) * 0.5;
        auto half_width_m =
            (nasrbrowse::lon_to_mx(bbox->lon_max) -
             nasrbrowse::lon_to_mx(bbox->lon_min)) * 0.5;
        auto needed = std::max(half_height_m,
                                  half_width_m / d.view.aspect_ratio());
        d.view.half_extent_y = needed * 1.2;
        // Force clamp by setting same extent through zoom(1.0).
        d.view.zoom(1.0);
    }

    d.needs_update = true;
    d.update_tiles();
}

void map_widget::set_imgui_wants_mouse(bool wants)
{
    pimpl->imgui_wants_mouse = wants;
}

void map_widget::set_imgui_wants_keyboard(bool wants)
{
    pimpl->imgui_wants_keyboard = wants;
}

double map_widget::zoom_level() const
{
    return pimpl->view.zoom_level();
}

const std::vector<std::unique_ptr<nasrbrowse::feature_type>>&
map_widget::feature_types() const
{
    return pimpl->feature_types;
}

void map_widget::button_event(sdl::input_button_t button, sdl::input_action_t action, sdl::input_mod_t)
{
    // Track button state for drag detection.
    if(action == sdl::input_action::release)
        pimpl->buttons_down.erase(button);
    else
        pimpl->buttons_down.insert(button);

    if(button.value != BUTTON_LEFT)
        return;

    if(action.value != 0) // press
    {
        pimpl->dragged = false;
        // If the press landed on a route waypoint or leg, start a drag;
        // this suppresses the normal pan + pick. The route gets selected
        // implicitly so the drag has the same visual affordance as a
        // drag on an already-selected route.
        // Waypoint hit takes priority over segment hit.
        if(pimpl->route && !pimpl->imgui_wants_mouse)
        {
            auto [lon, lat] = pimpl->ndc_to_lonlat(
                pimpl->cursor_ndc_x, pimpl->cursor_ndc_y);
            if(auto wp = pimpl->hit_route_waypoint(lon, lat))
            {
                pimpl->route_drag.mode = impl::route_drag_mode::waypoint;
                pimpl->route_drag.index = *wp;
                pimpl->set_route_selected(true);
            }
            else if(auto seg = pimpl->hit_route_segment(lon, lat))
            {
                pimpl->route_drag.mode = impl::route_drag_mode::segment;
                pimpl->route_drag.index = *seg;
                pimpl->set_route_selected(true);
            }
        }
    }
    else // release
    {
        auto mode = pimpl->route_drag.mode;
        pimpl->route_drag.mode = impl::route_drag_mode::none;
        if(mode != impl::route_drag_mode::none && pimpl->dragged)
        {
            pimpl->handle_route_drag_release(mode);
        }
        else if(!pimpl->dragged && !pimpl->imgui_wants_mouse)
        {
            pimpl->handle_pick();
        }
    }
}

bool map_widget::draw_imgui()
{
    // Both popups can coexist in theory, but in practice the selector is
    // dismissed as soon as a feature is chosen. Always draw both so either
    // one's warmup frames propagate upward.
    auto a = pimpl->draw_pick_imgui();
    auto b = pimpl->draw_info_imgui();

    if(pimpl->route_drag.mode != impl::route_drag_mode::none && pimpl->route)
    {
        const auto& wps = pimpl->route->waypoints;
        int i = pimpl->route_drag.index;
        auto cursor = ImGui::GetMousePos();
        auto* dl = ImGui::GetForegroundDrawList();
        auto col = IM_COL32(255, 255, 255, 220);

        auto draw_from = [&](int idx)
        {
            float x;
            float y;
            pimpl->view.world_to_pixel(
                nasrbrowse::waypoint_lon(wps[idx]),
                nasrbrowse::waypoint_lat(wps[idx]), x, y);
            dl->AddLine(ImVec2(x, y), cursor, col, 2.0F);
        };

        if(pimpl->route_drag.mode == impl::route_drag_mode::segment)
        {
            draw_from(i);
            draw_from(i + 1);
        }
        else  // waypoint: anchor to prev + next neighbors (if any)
        {
            if(i > 0) draw_from(i - 1);
            if(i + 1 < static_cast<int>(wps.size())) draw_from(i + 1);
        }
    }

    return a || b;
}

void map_widget::cursor_position_event(double xpos, double ypos)
{
    // Convert from window pixels to NDC via the projection matrix.
    auto ypos_flipped = pimpl->viewport_vec.w - ypos;
    glm::vec3 pixel_pos(xpos, ypos_flipped, 0.0);
    glm::vec3 pos(glm::unProject(pixel_pos, glm::mat4(1.0F),
                                  pimpl->projection_matrix, pimpl->viewport_vec));

    pimpl->cursor_ndc_x = pos[0];
    pimpl->cursor_ndc_y = pos[1];

    // If any button is held, dispatch as a drag.
    if(!pimpl->buttons_down.empty())
    {
        pimpl->dragged = true;
        if(pimpl->route_drag.mode != impl::route_drag_mode::none)
        {
            // Rubber-band follows cursor; force a redraw.
            pimpl->needs_update = true;
        }
        else
        {
            auto dx = pos[0] - pimpl->cursor_last_x;
            auto dy = pos[1] - pimpl->cursor_last_y;
            auto dx_meters = -dx * pimpl->view.half_extent_y * 2.0;
            auto dy_meters = -dy * pimpl->view.half_extent_y * 2.0;
            pimpl->view.pan_meters(dx_meters, dy_meters);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
        }
    }

    pimpl->cursor_last_x = pos[0];
    pimpl->cursor_last_y = pos[1];
}

void map_widget::key_event(sdl::input_key_t key, sdl::input_action_t action, sdl::input_mod_t)
{
    // Suppress pan/zoom keybindings while a text input has focus.
    if(pimpl->imgui_wants_keyboard) return;

    if(action != sdl::input_action::release)
    {
        switch(key.value)
        {
        case 'w':
        case 'W':
            pimpl->view.pan(0.0, 0.1);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
            break;
        case 's':
        case 'S':
            pimpl->view.pan(0.0, -0.1);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
            break;
        case 'a':
        case 'A':
            pimpl->view.pan(-0.1, 0.0);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
            break;
        case 'd':
        case 'D':
            pimpl->view.pan(0.1, 0.0);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
            break;
        case 'r':
        case 'R':
        {
            auto z = static_cast<int>(pimpl->view.zoom_level()) + 1;
            pimpl->view.zoom_to_level(z);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
            break;
        }
        case 'f':
        case 'F':
        {
            auto z = static_cast<int>(pimpl->view.zoom_level()) - 1;
            pimpl->view.zoom_to_level(z);
            pimpl->rebuild_grid();
            pimpl->update_tiles();
            break;
        }
        }
    }
}

void map_widget::scroll_event(double, double yoffset)
{
    auto factor = (yoffset > 0) ? 0.9 : 1.0 / 0.9;
    auto wx = pimpl->cursor_ndc_x * 2.0 * pimpl->view.half_extent_y + pimpl->view.center_x;
    auto wy = pimpl->cursor_ndc_y * 2.0 * pimpl->view.half_extent_y + pimpl->view.center_y;
    pimpl->view.zoom_at(factor, wx, wy);
    pimpl->rebuild_grid();
    pimpl->update_tiles();
}

void map_widget::framebuffer_size_event(int width, int height)
{
    if(height == 0) return;
    auto fwidth = static_cast<float>(width);
    auto fheight = static_cast<float>(height);
    pimpl->viewport_vec = glm::vec4(0.0F, 0.0F, fwidth, fheight);
    pimpl->normalized_viewport_width = fwidth / fheight;
    pimpl->projection_matrix = glm::orthoLH_ZO(
        -pimpl->normalized_viewport_width * 0.5F,
         pimpl->normalized_viewport_width * 0.5F,
        -0.5F, 0.5F, -1.0F, 1.0F);

    pimpl->view.viewport_width = width;
    pimpl->view.viewport_height = height;
    pimpl->rebuild_grid();
    pimpl->update_tiles();
}

bool map_widget::update()
{
    if(pimpl->tiles) pimpl->tiles->drain();

    auto new_candidates = pimpl->features.drain();
    if(new_candidates)
    {
        pimpl->labels.set_candidates(pimpl->features.labels());
    }

    // Reproject labels only when the view changed or new candidates arrived
    if(pimpl->needs_update || new_candidates)
    {
        pimpl->labels.update_positions(
            pimpl->view.center_x, pimpl->view.center_y,
            pimpl->view.half_extent_y,
            pimpl->view.viewport_width, pimpl->view.viewport_height,
            pimpl->vis);
    }

    auto result = pimpl->needs_update
        || (pimpl->tiles && pimpl->tiles->needs_upload())
        || pimpl->features.needs_upload() || pimpl->labels.needs_upload();

    if(result)
    {
        pimpl->needs_update = false;
    }
    return result;
}

std::vector<nasrbrowse::search_hit> map_widget::search(
    const std::string& query, int limit)
{
    return pimpl->pick_db.search(query, limit);
}

void map_widget::set_route_text(const std::string& text)
{
    if(text.empty())
    {
        clear_route();
        return;
    }
    // May throw route_parse_error; caller handles.
    pimpl->route.emplace(text, pimpl->pick_db);
    pimpl->features.set_route(pimpl->route);
    pimpl->route_selected = true;

    // Fit the view to the route's bounding box (20% padding), so the
    // pilot sees the whole route after pressing Set.
    const auto& wps = pimpl->route->waypoints;
    if(!wps.empty())
    {
        auto lat_min = nasrbrowse::waypoint_lat(wps[0]);
        auto lat_max = lat_min;
        auto lon_min = nasrbrowse::waypoint_lon(wps[0]);
        auto lon_max = lon_min;
        for(const auto& wp : wps)
        {
            auto la = nasrbrowse::waypoint_lat(wp);
            auto lo = nasrbrowse::waypoint_lon(wp);
            if(la < lat_min) lat_min = la;
            if(la > lat_max) lat_max = la;
            if(lo < lon_min) lon_min = lo;
            if(lo > lon_max) lon_max = lo;
        }

        auto& d = *pimpl;
        d.view.center_x = nasrbrowse::lon_to_mx((lon_min + lon_max) * 0.5);
        d.view.center_y = nasrbrowse::lat_to_my((lat_min + lat_max) * 0.5);

        auto is_point = (lon_min == lon_max && lat_min == lat_max);
        if(is_point)
        {
            constexpr int POINT_FOCUS_ZOOM = 12;
            d.view.zoom_to_level(POINT_FOCUS_ZOOM);
        }
        else
        {
            auto half_height_m =
                (nasrbrowse::lat_to_my(lat_max) -
                 nasrbrowse::lat_to_my(lat_min)) * 0.5;
            auto half_width_m =
                (nasrbrowse::lon_to_mx(lon_max) -
                 nasrbrowse::lon_to_mx(lon_min)) * 0.5;
            auto needed = std::max(half_height_m,
                                      half_width_m / d.view.aspect_ratio());
            d.view.half_extent_y = needed * 1.2;
            d.view.zoom(1.0);
        }
        pimpl->rebuild_grid();
    }

    pimpl->needs_update = true;
    // Kick the feature builder so the route renders without waiting
    // for a pan/zoom to resubmit.
    pimpl->update_tiles();
}

void map_widget::clear_route()
{
    pimpl->route.reset();
    pimpl->features.set_route(std::nullopt);
    pimpl->route_selected = false;
    pimpl->needs_update = true;
    pimpl->update_tiles();
}

const std::optional<nasrbrowse::flight_route>& map_widget::route() const
{
    return pimpl->route;
}

bool map_widget::drain_route_dirty()
{
    auto r = pimpl->route_dirty;
    pimpl->route_dirty = false;
    return r;
}

void map_widget::render_frame(sdl::command_buffer& cmd, sdl::texture& swapchain)
{
    auto& d = *pimpl;
    auto& ctx = d.render_ctx;
    ctx.projection_matrix = d.projection_matrix;
    ctx.normalized_viewport_width = d.normalized_viewport_width;

    auto s = static_cast<float>(1.0 / (2.0 * d.view.half_extent_y));
    auto cx = static_cast<float>(d.view.center_x);
    auto cy = static_cast<float>(d.view.center_y);
    auto view_matrix = glm::scale(glm::mat4(1.0F), glm::vec3(s, s, 1.0F)) *
                        glm::translate(glm::mat4(1.0F), glm::vec3(-cx, -cy, 0.0F));

    // Copy phase: upload pending vertex/texture data to GPU
    {
        sdl::copy_pass copy(cmd);
        if(!d.grid_vertices.empty())
        {
            d.grid_buffer.reset();
            auto buf = copy.create_and_upload_buffer(d.dev, sdl::buffer_usage::vertex, d.grid_vertices);
            d.grid_buffer = std::make_unique<sdl::buffer>(std::move(buf));
        }
        if(d.tiles) d.tiles->copy(copy);
        d.features.copy(copy);
        d.labels.copy(copy, d.dev);
    }

    // Render phase: one render pass with 5 pipeline stages
    sdl::render_pass pass(cmd, swapchain, 0.1F, 0.1F, 0.12F, 1.0F);

    // Textured triangles (tile basemap)
    pass.bind_pipeline(d.textured_pipeline);
    ctx.current_pass = nasrbrowse::render_pass_id::textured_trianglelist_0;
    if(d.show_tiles && d.tiles)
        d.tiles->render(pass, ctx, view_matrix);

    // Polygon fills (airspace/SUA selection highlights)
    pass.bind_pipeline(d.trianglelist_pipeline);
    ctx.current_pass = nasrbrowse::render_pass_id::polygon_fill_0;
    d.features.render(pass, ctx, view_matrix);

    // Lines (grid overlay)
    pass.bind_pipeline(d.linelist_pipeline);
    ctx.current_pass = nasrbrowse::render_pass_id::trianglelist_0;
    if(d.grid_buffer && d.grid_buffer->count() > 0)
    {
        sdl::uniform_buffer uniforms;
        uniforms.projection_matrix = ctx.projection_matrix;
        pass.push_vertex_uniforms(0, &uniforms, sizeof(uniforms));
        pass.push_fragment_uniforms(0, &uniforms, sizeof(uniforms));
        pass.bind_vertex_buffer(*d.grid_buffer);
        pass.draw(d.grid_buffer->count());
    }

    // SDF lines (feature polylines)
    pass.bind_pipeline(d.line_sdf_pipeline);
    ctx.current_pass = nasrbrowse::render_pass_id::line_sdf_0;
    d.features.render(pass, ctx, view_matrix);

    // Text labels (reuse textured pipeline)
    pass.bind_pipeline(d.textured_pipeline);
    ctx.current_pass = nasrbrowse::render_pass_id::text_labels_0;
    d.labels.render(pass, ctx, d.text_sampler,
                     d.view.viewport_width, d.view.viewport_height);
}
