#include "map_widget.hpp"
#include "chart_style.hpp"
#include "ephemeral_data.hpp"
#include "feature_renderer.hpp"
#include "feature_type.hpp"
#include "geo_math.hpp"
#include "ini_config.hpp"
#include "label_renderer.hpp"
#include "map_view.hpp"
#include "nasr_database.hpp"
#include "pick_result.hpp"
#include "render_context.hpp"
#include "tile_renderer.hpp"
#include "ui_overlay.hpp"
#include "ui_popup_manager.hpp"
#include <glm/ext/matrix_clip_space.hpp>
#include <glm/ext/matrix_projection.hpp>
#include <glm/ext/matrix_transform.hpp>
#include <algorithm>
#include <cassert>
#include <iostream>
#include <memory>
#include <sdl/buffer.hpp>
#include <sdl/command_buffer.hpp>
#include <sdl/copy_pass.hpp>
#include <sdl/device.hpp>
#include <sdl/log.hpp>
#include <sdl/event.hpp>
#include <sdl/pipeline.hpp>
#include <sdl/render_pass.hpp>
#include <sdl/shader.hpp>
#include <sdl/types.hpp>
#include <sstream>
#include <string>
#include <unordered_set>
#include <vector>

// Shader bytecode (generated by shader compilation)
#include <default_frag_spv.h>
#include <default_vert_spv.h>
#include <line_frag_spv.h>
#include <line_vert_spv.h>
#include <textured_frag_spv.h>
#include <textured_vert_spv.h>
#ifdef __APPLE__
#include <default_frag_metal.h>
#include <default_vert_metal.h>
#include <line_frag_metal.h>
#include <line_vert_metal.h>
#include <textured_frag_metal.h>
#include <textured_vert_metal.h>
#endif
#ifdef OSECT_HAVE_METALLIB
#include <default_metallib.h>
#include <line_metallib.h>
#include <textured_metallib.h>
#endif
#ifdef OSECT_HAVE_DXIL
#include <default_frag_dxil.h>
#include <default_vert_dxil.h>
#include <line_frag_dxil.h>
#include <line_vert_dxil.h>
#include <textured_frag_dxil.h>
#include <textured_vert_dxil.h>
#endif

namespace
{
    // Shader data loading, from xxd-produced headers
    enum class shader_id
    {
        DEFAULT,
        LINE,
        TEXTURED
    };

    struct shader_bytecode
    {
        const unsigned char* data;
        unsigned int len;
    };

    // NOLINTBEGIN(cppcoreguidelines-pro-bounds-array-to-pointer-decay)
    // Shader bytecode is a generated C array that decays to a pointer
    // when stored in shader_bytecode.
    shader_bytecode get_spirv_bytecode(shader_id id, sdl::shader_stage_t stage)
    {
        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                return {default_vert_spv, default_vert_spv_len};
            case shader_id::LINE:
                return {line_vert_spv, line_vert_spv_len};
            case shader_id::TEXTURED:
                return {textured_vert_spv, textured_vert_spv_len};
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                return {default_frag_spv, default_frag_spv_len};
            case shader_id::LINE:
                return {line_frag_spv, line_frag_spv_len};
            case shader_id::TEXTURED:
                return {textured_frag_spv, textured_frag_spv_len};
            }
        }
        return {nullptr, 0};
    }

#ifdef OSECT_HAVE_DXIL
    shader_bytecode get_dxil_bytecode(shader_id id, sdl::shader_stage_t stage)
    {
        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                return {default_vert_dxil, default_vert_dxil_len};
            case shader_id::LINE:
                return {line_vert_dxil, line_vert_dxil_len};
            case shader_id::TEXTURED:
                return {textured_vert_dxil, textured_vert_dxil_len};
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                return {default_frag_dxil, default_frag_dxil_len};
            case shader_id::LINE:
                return {line_frag_dxil, line_frag_dxil_len};
            case shader_id::TEXTURED:
                return {textured_frag_dxil, textured_frag_dxil_len};
            }
        }
        return {nullptr, 0};
    }
#endif

#ifdef __APPLE__
    shader_bytecode get_msl_bytecode(shader_id id, sdl::shader_stage_t stage)
    {
        if(stage == sdl::shader_stage::vertex)
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                return {default_vert_metal, default_vert_metal_len};
            case shader_id::LINE:
                return {line_vert_metal, line_vert_metal_len};
            case shader_id::TEXTURED:
                return {textured_vert_metal, textured_vert_metal_len};
            }
        }
        else
        {
            switch(id)
            {
            case shader_id::DEFAULT:
                return {default_frag_metal, default_frag_metal_len};
            case shader_id::LINE:
                return {line_frag_metal, line_frag_metal_len};
            case shader_id::TEXTURED:
                return {textured_frag_metal, textured_frag_metal_len};
            }
        }
        return {nullptr, 0};
    }
#endif

#ifdef OSECT_HAVE_METALLIB
    shader_bytecode get_metallib_bytecode(shader_id id)
    {
        switch(id)
        {
        case shader_id::DEFAULT:
            return {default_metallib, default_metallib_len};
        case shader_id::LINE:
            return {line_metallib, line_metallib_len};
        case shader_id::TEXTURED:
            return {textured_metallib, textured_metallib_len};
        }
        return {nullptr, 0};
    }
#endif

    sdl::shader load_shader(const sdl::device& dev, shader_id id, sdl::shader_stage_t stage, uint32_t num_samplers = 0,
                            uint32_t num_storage_buffers = 0)
    {
        const auto* entrypoint = (stage == sdl::shader_stage::vertex) ? "vertex_main" : "fragment_main";
        auto format = dev.get_shader_format();
        shader_bytecode bc = {nullptr, 0};
#ifdef OSECT_HAVE_METALLIB
        if(format == sdl::shader_format::metallib)
        {
            bc = get_metallib_bytecode(id);
        }
        else
#endif
#ifdef __APPLE__
            if(format == sdl::shader_format::msl)
            bc = get_msl_bytecode(id, stage);
        else
#endif
#ifdef OSECT_HAVE_DXIL
            if(format == sdl::shader_format::dxil)
            bc = get_dxil_bytecode(id, stage);
        else
#endif
            bc = get_spirv_bytecode(id, stage);
        return {dev, bc.data, bc.len, entrypoint, stage, format, num_samplers, num_storage_buffers};
    }
    // NOLINTEND(cppcoreguidelines-pro-bounds-array-to-pointer-decay)
}

// Pick box size in pixels (width and height of the pick region for point features)
constexpr auto PICK_BOX_SIZE_PIXELS = 20;

// Exact-point short-circuit radius: a single point feature this close to the
// cursor skips the candidate-selector popup and logs directly.
constexpr auto PICK_BOX_EXACT_SIZE_PIXELS = 4;

// SDL left mouse button value
constexpr uint8_t BUTTON_LEFT = 1;

namespace osect
{

    struct map_widget::impl : public sdl::event_listener
    {
        map_view view;
        sdl::device& dev;
        bool needs_update = true;
        bool show_tiles = true;

        // GPU pipelines (created once at construction)
        sdl::pipeline linelist_pipeline;
        sdl::pipeline trianglelist_pipeline;
        sdl::pipeline textured_pipeline;
        sdl::pipeline line_sdf_pipeline;

        // Tile renderer for raster basemap (null if no basemap was provided)
        std::unique_ptr<tile_renderer> tiles;

        // Vector feature renderer
        feature_renderer features;

        // Grid line vertex buffer (rebuilt on viewport change)
        std::vector<sdl::vertex_t2f_c4ub_v3f> grid_vertices;
        std::unique_ptr<sdl::buffer> grid_buffer;

        // Label renderer
        label_renderer labels;

        // Render context (projection, sampler, pass ID)
        render_context render_ctx;

        // NASR database for picks and search
        nasr_database pick_db;
        ephemeral_data& eph;
        chart_style styles;
        layer_visibility vis;
        double cursor_ndc_x = 0.0;
        double cursor_ndc_y = 0.0;
        bool dragged = false;
        bool imgui_wants_mouse = false;
        // True while a left-button drag that originated on the map
        // (i.e. ImGui did not own the mouse at press time) is in
        // progress. Gates pan in cursor_position_event so dragging an
        // ImGui scrollbar or selecting text in a text box does not
        // also pan the map.
        bool pan_drag_active = false;
        bool imgui_wants_keyboard = false;

        popup_manager popups;

        std::vector<std::unique_ptr<feature_type>> feature_types;

        std::vector<flight_route> routes;
        // Two independent route-role indexes:
        //   * active_route_index — the panel / drag target, driven by
        //     which tab is focused in the route panel.
        //   * selected_route_index — the route whose info popup is
        //     open and which renders in white + halos, driven by
        //     clicks on the map. Either, both, or neither may be set.
        std::optional<std::size_t> active_route_index;
        std::optional<std::size_t> selected_route_index;
        bool route_dirty = false;
        // The route the user requested be deleted via the info
        // popup's Delete button, since the last drain. Caller owns
        // the lifecycle so it can close the corresponding panel tab
        // in the same operation.
        std::optional<std::size_t> route_delete_request;
        // The non-active route the user clicked since the last
        // drain. Caller switches the panel tab to the matching tab.
        std::optional<std::size_t> route_activate_request;

        flight_route* active_route()
        {
            if(!active_route_index || *active_route_index >= routes.size())
            {
                return nullptr;
            }
            return &routes[*active_route_index];
        }
        const flight_route* active_route() const
        {
            if(!active_route_index || *active_route_index >= routes.size())
            {
                return nullptr;
            }
            return &routes[*active_route_index];
        }

        // Route drag state. Waypoint hit takes priority over segment hit so
        // dragging an existing waypoint doesn't get mistaken for an insert.
        enum class route_drag_mode
        {
            none,
            segment,
            waypoint
        };
        struct
        {
            route_drag_mode mode = route_drag_mode::none;
            std::size_t index = 0; // segment index (segment mode) or wp index (waypoint mode)
        } route_drag;

        // Event dispatch state
        glm::mat4 projection_matrix{1.0F};
        float normalized_viewport_width = 1.0F;
        glm::vec4 viewport_vec{0.0F};
        std::unordered_set<sdl::input_button_t> buttons_down;
        double cursor_last_x = 0;
        double cursor_last_y = 0;

        impl(sdl::device& dev, const char* tile_path, const char* db_path, const ini_config& ini, ephemeral_data& eph,
             int viewport_width, int viewport_height)
            : dev(dev),
              linelist_pipeline(dev, load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::vertex),
                                load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::fragment),
                                sdl::primitive_type::line_list),
              trianglelist_pipeline(dev, load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::vertex),
                                    load_shader(dev, shader_id::DEFAULT, sdl::shader_stage::fragment),
                                    sdl::primitive_type::triangle_list),
              textured_pipeline(dev, load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::vertex),
                                load_shader(dev, shader_id::TEXTURED, sdl::shader_stage::fragment, 1),
                                sdl::primitive_type::triangle_list),
              line_sdf_pipeline(dev, load_shader(dev, shader_id::LINE, sdl::shader_stage::vertex, 0, 2),
                                load_shader(dev, shader_id::LINE, sdl::shader_stage::fragment, 0, 2),
                                sdl::primitive_type::triangle_list, sdl::texture_format_t(0), false),
              tiles(tile_path ? std::make_unique<tile_renderer>(dev, tile_path) : nullptr),
              features(dev, db_path, chart_style(ini), eph),
              labels(dev),
              pick_db(db_path),
              eph(eph),
              styles(ini),
              feature_types(make_feature_types())
        {
            set_viewport(viewport_width, viewport_height);
        }

        void rebuild_grid()
        {
            grid_vertices.clear();

            auto vx_min = view.view_x_min();
            auto vx_max = view.view_x_max();
            auto vy_min = view.view_y_min();
            auto vy_max = view.view_y_max();
            auto range_x = vx_max - vx_min;
            auto range_y = vy_max - vy_min;

            // Normalize coordinates to -0.5..0.5 for rendering
            auto to_ndc_x = [&](double mx) -> float
            { return static_cast<float>(((mx - vx_min) / range_x - 0.5) * view.aspect_ratio()); };
            auto to_ndc_y = [&](double my) -> float { return static_cast<float>((my - vy_min) / range_y - 0.5); };

            // Draw grid lines at regular lat/lon intervals
            // Choose interval based on zoom level
            auto approx_zoom = view.zoom_level();
            double grid_step = 0.5;
            if(approx_zoom < 3)
            {
                grid_step = 30.0;
            }
            else if(approx_zoom < 5)
            {
                grid_step = 10.0;
            }
            else if(approx_zoom < 7)
            {
                grid_step = 5.0;
            }
            else if(approx_zoom < 9)
            {
                grid_step = 1.0;
            }
            auto lon_step = grid_step;
            auto lat_step = grid_step;

            // Grid line color: dark gray, semi-transparent
            uint8_t r = 80;
            uint8_t g = 80;
            uint8_t b = 80;
            uint8_t a = 160;

            // Longitude lines (vertical)
            auto lon_min = mx_to_lon(vx_min);
            auto lon_max = mx_to_lon(vx_max);
            auto lon_start = std::floor(lon_min / lon_step) * lon_step;
            auto lon_count = static_cast<int>((lon_max - lon_start) / lon_step) + 1;
            for(int i = 0; i < lon_count; ++i)
            {
                auto lon = lon_start + i * lon_step;
                auto mx = lon_to_mx(lon);
                auto nx = to_ndc_x(mx);
                auto ny0 = to_ndc_y(vy_min);
                auto ny1 = to_ndc_y(vy_max);
                grid_vertices.push_back({0, 0, r, g, b, a, nx, ny0, 0});
                grid_vertices.push_back({0, 0, r, g, b, a, nx, ny1, 0});
            }

            // Latitude lines (horizontal, non-uniform spacing in Mercator)
            auto lat_min = my_to_lat(vy_min);
            auto lat_max = my_to_lat(vy_max);
            auto lat_start = std::floor(lat_min / lat_step) * lat_step;
            auto lat_count = static_cast<int>((lat_max - lat_start) / lat_step) + 1;
            for(int i = 0; i < lat_count; ++i)
            {
                auto lat = lat_start + i * lat_step;
                auto my = lat_to_my(lat);
                auto ny = to_ndc_y(my);
                auto nx0 = to_ndc_x(vx_min);
                auto nx1 = to_ndc_x(vx_max);
                grid_vertices.push_back({0, 0, r, g, b, a, nx0, ny, 0});
                grid_vertices.push_back({0, 0, r, g, b, a, nx1, ny, 0});
            }

            needs_update = true;
        }

        void update_tiles()
        {
            if(tiles)
            {
                tiles->update(view.view_x_min(), view.view_y_min(), view.view_x_max(), view.view_y_max(),
                              view.half_extent_y, view.viewport_height, view.aspect_ratio());
            }
            features.update(view.view_x_min(), view.view_y_min(), view.view_x_max(), view.view_y_max(),
                            view.half_extent_y, view.viewport_height, view.aspect_ratio());
        }

        pick_result pick_at(double ndc_x, double ndc_y)
        {
            using namespace osect;

            // NDC → Web Mercator → lon/lat, wrapping lon to [-180, 180] for DB.
            auto world_x = ndc_x * 2.0 * view.half_extent_y + view.center_x;
            auto world_y = ndc_y * 2.0 * view.half_extent_y + view.center_y;
            auto click_lon = mx_to_lon(world_x);
            auto click_lat = my_to_lat(world_y);
            click_lon = std::fmod(click_lon + 180.0, 360.0);
            if(click_lon < 0)
            {
                click_lon += 360.0;
            }
            click_lon -= 180.0;

            // Point-feature pick box: pixel half-size → world coords.
            auto pick_half_ndc = (PICK_BOX_SIZE_PIXELS * 0.5) / view.viewport_height;
            auto box_world_half = pick_half_ndc * 2.0 * view.half_extent_y;
            auto box_lon_half = mx_to_lon(box_world_half);
            geo_bbox pick_box{click_lon - box_lon_half, my_to_lat(world_y - box_world_half), click_lon + box_lon_half,
                              my_to_lat(world_y + box_world_half)};
            geo_bbox click_box{click_lon, click_lat, click_lon, click_lat};

            pick_context ctx{
                pick_db,   eph,       styles,   vis,       view.zoom_level(),
                click_lon, click_lat, pick_box, click_box, (pick_box.lat_max - pick_box.lat_min) * 0.5 * 60.0};

            pick_result result;
            result.lon = click_lon;
            result.lat = click_lat;
            for(const auto& obj : feature_types)
            {
                if(vis[obj->layer_id()])
                {
                    obj->pick(ctx, result.features);
                }
            }
            return result;
        }

        // NDC → world lon/lat (same math pick_at uses to derive click_lon/lat,
        // without running the feature-type pick pass).
        std::pair<double, double> ndc_to_lonlat(double ndc_x, double ndc_y) const
        {
            auto world_x = ndc_x * 2.0 * view.half_extent_y + view.center_x;
            auto world_y = ndc_y * 2.0 * view.half_extent_y + view.center_y;
            auto lon = mx_to_lon(world_x);
            auto lat = my_to_lat(world_y);
            lon = std::fmod(lon + 180.0, 360.0);
            if(lon < 0)
            {
                lon += 360.0;
            }
            lon -= 180.0;
            return {lon, lat};
        }

        // Distance from point p to the segment a-b (pixel space).
        static double point_segment_distance_px(pixel_pos p, pixel_pos a, pixel_pos b)
        {
            auto dx = b.x - a.x;
            auto dy = b.y - a.y;
            auto len_sq = dx * dx + dy * dy;
            auto t = 0.0;
            if(len_sq > 0)
            {
                t = ((p.x - a.x) * dx + (p.y - a.y) * dy) / len_sq;
            }
            t = std::clamp(t, 0.0, 1.0);
            auto cx = a.x + t * dx;
            auto cy = a.y + t * dy;
            return std::sqrt((p.x - cx) * (p.x - cx) + (p.y - cy) * (p.y - cy));
        }

        // The active route's pick under the cursor (preferring
        // waypoint over leg per the per-route priority in
        // collect_route_picks). nullopt if no route is active or the
        // active route is not under the cursor.
        std::optional<route_pick_item> active_route_pick(double click_lon, double click_lat) const
        {
            if(!active_route_index)
            {
                return std::nullopt;
            }
            for(const auto& p : collect_route_picks(click_lon, click_lat))
            {
                if(p.route_index == *active_route_index)
                {
                    return p;
                }
            }
            return std::nullopt;
        }

        // Scan every route for a hit under the cursor and collect
        // one route_pick_item per route that's hit. Waypoints take
        // priority over legs within a single route, and once a
        // route's waypoint is hit we skip its legs (the waypoint is
        // the more specific target). Returned items are in route-
        // vector order.
        std::vector<route_pick_item> collect_route_picks(double click_lon, double click_lat) const
        {
            std::vector<route_pick_item> hits;
            auto cursor = view.world_to_pixel(click_lon, click_lat);
            const auto threshold = PICK_BOX_SIZE_PIXELS * 0.5F;

            for(std::size_t r = 0; r < routes.size(); ++r)
            {
                const auto& wps = routes[r].waypoints;

                bool found_waypoint = false;
                for(std::size_t i = 0; i < wps.size(); ++i)
                {
                    auto wp = view.world_to_pixel(waypoint_lon(wps[i]), waypoint_lat(wps[i]));
                    auto dx = wp.x - cursor.x;
                    auto dy = wp.y - cursor.y;
                    if(dx * dx + dy * dy < threshold * threshold)
                    {
                        hits.push_back({r, route_pick_item::kind::waypoint, i});
                        found_waypoint = true;
                        break;
                    }
                }
                if(found_waypoint)
                {
                    continue;
                }

                if(wps.size() < 2)
                {
                    continue;
                }
                bool found_leg = false;
                for(std::size_t i = 1; i < wps.size() && !found_leg; ++i)
                {
                    auto arc = geodesic_interpolate(waypoint_lat(wps[i - 1]), waypoint_lon(wps[i - 1]),
                                                    waypoint_lat(wps[i]), waypoint_lon(wps[i]));
                    for(std::size_t j = 1; j < arc.size(); ++j)
                    {
                        auto a = view.world_to_pixel(arc[j - 1].lon, arc[j - 1].lat);
                        auto b = view.world_to_pixel(arc[j].lon, arc[j].lat);
                        if(point_segment_distance_px(cursor, a, b) < threshold)
                        {
                            hits.push_back({r, route_pick_item::kind::leg, i - 1});
                            found_leg = true;
                            break;
                        }
                    }
                }
            }
            return hits;
        }

        // Resolve a release point to a route_waypoint: prefer the first
        // airport/navaid/fix under the cursor; otherwise lat/lon at the click.
        route_waypoint resolve_release_waypoint()
        {
            auto pick = pick_at(cursor_ndc_x, cursor_ndc_y);
            for(const auto& f : pick.features)
            {
                if(std::holds_alternative<airport>(f))
                {
                    const auto& a = std::get<airport>(f);
                    return airport_ref{a.arpt_id, a};
                }
                if(std::holds_alternative<navaid>(f))
                {
                    const auto& n = std::get<navaid>(f);
                    return navaid_ref{n.nav_id, n};
                }
                if(std::holds_alternative<fix>(f))
                {
                    const auto& x = std::get<fix>(f);
                    return fix_ref{x.fix_id, x};
                }
            }
            return route_waypoint{latlon_ref{pick.lat, pick.lon}};
        }

        void notify_route_changed()
        {
            features.set_routes(routes, active_route_index, selected_route_index);
            route_dirty = true;
            needs_update = true;
        }

        void handle_route_drag_release(route_drag_mode mode)
        {
            auto* r = active_route();
            if(!r)
            {
                return;
            }
            if(mode == route_drag_mode::segment)
            {
                auto wp = resolve_release_waypoint();
                sdl::log_info("route insert: index=" + std::to_string(route_drag.index) + " waypoint="
                              + waypoint_id(wp));
                r->insert_waypoint(route_drag.index, wp, pick_db);
                notify_route_changed();
                return;
            }

            // Waypoint mode. If release lands on an adjacent waypoint, delete
            // the dragged waypoint (but only if the route keeps >= 2
            // waypoints afterward). Otherwise replace it with whatever's
            // under the cursor.
            auto i = route_drag.index;
            auto [lon, lat] = ndc_to_lonlat(cursor_ndc_x, cursor_ndc_y);
            auto pick = active_route_pick(lon, lat);
            std::optional<std::size_t> hit;
            if(pick && pick->k == route_pick_item::kind::waypoint)
            {
                hit = pick->inner_index;
            }
            auto adjacent = hit && ((i > 0 && *hit == i - 1) || *hit == i + 1);

            if(adjacent && r->waypoints.size() > 2)
            {
                sdl::log_info("route delete: index=" + std::to_string(i));
                r->delete_waypoint(i, pick_db);
            }
            else
            {
                auto wp = resolve_release_waypoint();
                sdl::log_info("route replace: index=" + std::to_string(i) + " -> " + waypoint_id(wp));
                r->replace_waypoint(i, std::move(wp), pick_db);
            }
            notify_route_changed();
        }

        // Compute the centroid of a route's waypoints. Used as the
        // popup anchor when no click coords are available.
        std::pair<double, double> route_centroid(std::size_t index) const
        {
            assert(index < routes.size());
            auto sum_lon = 0.0;
            auto sum_lat = 0.0;
            const auto& wps = routes[index].waypoints;
            for(const auto& wp : wps)
            {
                sum_lon += waypoint_lon(wp);
                sum_lat += waypoint_lat(wp);
            }
            auto n = static_cast<double>(wps.size());
            return {sum_lon / n, sum_lat / n};
        }

        // Set the selected route, opening or closing the route info
        // popup to match. nullopt closes the popup and clears the
        // highlight. `anchor`, when set, places the popup at those
        // world coordinates (typically the click point); when unset,
        // the popup is anchored at the route's centroid.
        void select_route(std::optional<std::size_t> index,
                          std::optional<std::pair<double, double>> anchor = std::nullopt)
        {
            assert(!index || *index < routes.size());

            bool target_open = index.has_value();
            bool unchanged = popups.route_open() == target_open && selected_route_index == index;

            if(target_open)
            {
                auto [alon, alat] = anchor ? *anchor : route_centroid(*index);
                popups.open_route(alon, alat);
            }
            else if(!unchanged)
            {
                popups.close_route();
            }

            if(unchanged)
            {
                return;
            }

            selected_route_index = index;
            features.set_routes(routes, active_route_index, selected_route_index);
            needs_update = true;
        }

        // Geographic centroid of the active route's waypoints. Used as
        // the popup anchor when the route popup is opened programmatically
        // (no click point).
        std::pair<double, double> active_route_centroid() const
        {
            const auto* r = active_route();
            auto sum_lon = 0.0;
            auto sum_lat = 0.0;
            const auto& wps = r->waypoints;
            for(const auto& wp : wps)
            {
                sum_lon += waypoint_lon(wp);
                sum_lat += waypoint_lat(wp);
            }
            auto n = static_cast<double>(wps.size());
            return {sum_lon / n, sum_lat / n};
        }

        // Drop a single route. Adjusts active_route_index and
        // selected_route_index so each still points to a valid route
        // (or becomes nullopt). The selected popup is closed if the
        // selected route was the one removed. Flags route_dirty so
        // the main loop re-pushes UI state.
        void erase_route_at(std::size_t index)
        {
            assert(index < routes.size());
            routes.erase(routes.begin() + static_cast<std::ptrdiff_t>(index));

            auto adjust = [&](std::optional<std::size_t>& idx)
            {
                if(!idx)
                {
                    return;
                }
                if(routes.empty() || *idx == index)
                {
                    idx.reset();
                }
                else if(*idx > index)
                {
                    --*idx;
                }
            };
            auto selected_was_removed = selected_route_index && *selected_route_index == index;
            adjust(active_route_index);
            adjust(selected_route_index);
            if(selected_was_removed || routes.empty())
            {
                popups.close_route();
            }
            features.set_routes(routes, active_route_index, selected_route_index);
            route_dirty = true;
            needs_update = true;
        }

        // Open (or replace) the info popup showing details for a selected feature.
        void open_info_popup(const feature& f, double click_lon, double click_lat)
        {
            auto [alon, alat] = find_feature_type(feature_types, f).anchor_lonlat(f, click_lon, click_lat);
            popups.open_info(f, alon, alat);
            features.set_selection(f);
            select_route(std::nullopt);
            needs_update = true;
        }

        void close_info_popup()
        {
            popups.close_info();
            features.set_selection(std::nullopt);
            needs_update = true;
        }

        // Apply a single pick — either a feature (open info popup)
        // or a route entity (select if it's the active route, queue
        // an activate request if it's a non-active route).
        void act_on_pick(const pick_item& item, double click_lon, double click_lat)
        {
            if(std::holds_alternative<route_pick_item>(item))
            {
                const auto& r = std::get<route_pick_item>(item);
                close_info_popup();
                if(active_route_index && *active_route_index == r.route_index)
                {
                    sdl::log_info("pick: active route selected");
                    select_route(active_route_index, std::pair{click_lon, click_lat});
                }
                else
                {
                    sdl::log_info("pick: activate route index=" + std::to_string(r.route_index));
                    route_activate_request = r.route_index;
                    needs_update = true;
                }
                return;
            }
            const auto& f = std::get<feature>(item);
            sdl::log_info("pick: " + find_feature_type(feature_types, f).summary(f));
            open_info_popup(f, click_lon, click_lat);
        }

        // Handle a completed left-click pick. Gather all candidates
        // (feature picks + route waypoints/legs), then either fast-
        // path a single hit, short-circuit a precise feature click,
        // or open the multi-hit selector with disambiguating labels.
        void handle_pick()
        {
            popups.close_pick();

            auto result = pick_at(cursor_ndc_x, cursor_ndc_y);
            auto route_picks = collect_route_picks(result.lon, result.lat);

            // Exact-point short-circuit for feature-only clicks: a
            // precise click on a single point feature opens its info
            // popup directly even when looser features are also
            // nearby. Disabled when routes are at the click — the
            // selector should appear so the user can choose between
            // routes and the underlying feature.
            if(route_picks.empty())
            {
                const double exact_threshold_px = PICK_BOX_EXACT_SIZE_PIXELS;
                auto exact_count = 0;
                const feature* exact_hit = nullptr;
                for(const auto& f : result.features)
                {
                    auto coord = find_feature_type(feature_types, f).point_coord(f);
                    if(!coord)
                    {
                        continue;
                    }
                    auto fp = view.world_to_pixel(coord->first, coord->second);
                    auto cp = view.world_to_pixel(result.lon, result.lat);
                    auto dx = fp.x - cp.x;
                    auto dy = fp.y - cp.y;
                    if(std::sqrt(dx * dx + dy * dy) <= exact_threshold_px)
                    {
                        ++exact_count;
                        exact_hit = &f;
                    }
                }
                if(exact_count == 1)
                {
                    open_info_popup(*exact_hit, result.lon, result.lat);
                    return;
                }
            }

            // Build the candidate list: routes first (so they appear
            // at the top of the picker), then features.
            std::vector<pick_item> items;
            items.reserve(route_picks.size() + result.features.size());
            for(const auto& r : route_picks)
            {
                items.emplace_back(r);
            }
            for(auto& f : result.features)
            {
                items.emplace_back(std::move(f));
            }

            if(items.empty())
            {
                return;
            }
            if(items.size() == 1)
            {
                act_on_pick(items[0], result.lon, result.lat);
                return;
            }

            sdl::log_info("pick: selector with " + std::to_string(items.size()) + " candidates");
            close_info_popup();
            select_route(std::nullopt);
            popups.open_pick(std::move(items), result.lon, result.lat);
            needs_update = true;
        }

        // Draw all popups via the popup_manager. Returns true if another
        // render frame is needed for warmup.
        bool draw_popups()
        {
            auto out = popups.draw(view, feature_types, routes, selected_route_index);

            // Apply side effects of user actions.
            if(out.pick_selected)
            {
                // The manager already closed the picker; act on the
                // chosen item the same way as if it were the only
                // hit at the click point.
                act_on_pick(out.pick_selected->picked, out.pick_selected->click_lon, out.pick_selected->click_lat);
            }
            if(out.info_dismissed)
            {
                features.set_selection(std::nullopt);
                needs_update = true;
            }
            if(out.route_dismissed)
            {
                // Manager already closed the popup; clear selection so
                // the route loses its highlight too.
                selected_route_index.reset();
                features.set_routes(routes, active_route_index, selected_route_index);
                needs_update = true;
            }
            if(out.route_delete && selected_route_index)
            {
                // Manager already closed the popup. Surface the
                // index for the caller to handle (so it can close
                // the corresponding panel tab in the same operation)
                // and immediately un-highlight the route, otherwise
                // the user sees a one-frame flash of white + halos
                // with no popup.
                route_delete_request = selected_route_index;
                selected_route_index.reset();
                features.set_routes(routes, active_route_index, selected_route_index);
                needs_update = true;
            }

            return out.needs_more_frames;
        }

        void button_event(sdl::input_button_t button, sdl::input_action_t action, sdl::input_mod_t /*mods*/) override
        {
            // Track button state for drag detection.
            if(action == sdl::input_action::release)
            {
                buttons_down.erase(button);
            }
            else
            {
                buttons_down.insert(button);
            }

            if(button.value != BUTTON_LEFT)
            {
                return;
            }

            if(action.value != 0) // press
            {
                dragged = false;
                // Capture ImGui ownership at press time. A drag that
                // started inside an ImGui widget (scrollbar, text input,
                // etc.) must NOT pan the map even if the cursor leaves
                // the widget mid-drag.
                pan_drag_active = !imgui_wants_mouse;
                // If the press landed on the active route's waypoint or leg,
                // start a drag; this suppresses the normal pan + pick. The
                // route gets selected implicitly so the drag has the same
                // visual affordance as a drag on an already-selected route.
                // active_route_pick prefers waypoints over legs per route.
                if(!imgui_wants_mouse)
                {
                    auto [lon, lat] = ndc_to_lonlat(cursor_ndc_x, cursor_ndc_y);
                    if(auto pick = active_route_pick(lon, lat))
                    {
                        route_drag.mode = pick->k == route_pick_item::kind::waypoint
                                              ? route_drag_mode::waypoint
                                              : route_drag_mode::segment;
                        route_drag.index = pick->inner_index;
                        select_route(active_route_index, std::pair{lon, lat});
                    }
                }
            }
            else // release
            {
                auto mode = route_drag.mode;
                route_drag.mode = route_drag_mode::none;
                pan_drag_active = false;
                if(mode != route_drag_mode::none && dragged)
                {
                    handle_route_drag_release(mode);
                }
                else if(!dragged && !imgui_wants_mouse)
                {
                    handle_pick();
                }
            }
        }

        void cursor_position_event(double xpos, double ypos) override
        {
            // Convert from window pixels to NDC via the projection matrix.
            auto ypos_flipped = viewport_vec.w - ypos;
            glm::vec3 pixel_pos(xpos, ypos_flipped, 0.0);
            glm::vec3 pos(glm::unProject(pixel_pos, glm::mat4(1.0F), projection_matrix, viewport_vec));

            cursor_ndc_x = pos[0];
            cursor_ndc_y = pos[1];

            // If any button is held, dispatch as a drag.
            if(!buttons_down.empty())
            {
                dragged = true;
                if(route_drag.mode != route_drag_mode::none)
                {
                    // Rubber-band follows cursor; force a redraw.
                    needs_update = true;
                }
                else if(pan_drag_active)
                {
                    auto dx = pos[0] - cursor_last_x;
                    auto dy = pos[1] - cursor_last_y;
                    auto dx_meters = -dx * view.half_extent_y * 2.0;
                    auto dy_meters = -dy * view.half_extent_y * 2.0;
                    view.pan_meters(dx_meters, dy_meters);
                    rebuild_grid();
                }
            }

            cursor_last_x = pos[0];
            cursor_last_y = pos[1];
        }

        void key_event(sdl::input_key_t key, sdl::input_action_t action, sdl::input_mod_t /*mods*/) override
        {
            // Suppress pan/zoom keybindings while a text input has focus.
            if(imgui_wants_keyboard)
            {
                return;
            }

            if(action != sdl::input_action::release)
            {
                switch(key.value)
                {
                case 'w':
                case 'W':
                    view.pan(0.0, 0.1);
                    rebuild_grid();
                    break;
                case 's':
                case 'S':
                    view.pan(0.0, -0.1);
                    rebuild_grid();
                    break;
                case 'a':
                case 'A':
                    view.pan(-0.1, 0.0);
                    rebuild_grid();
                    break;
                case 'd':
                case 'D':
                    view.pan(0.1, 0.0);
                    rebuild_grid();
                    break;
                case 'r':
                case 'R':
                {
                    auto z = static_cast<int>(view.zoom_level()) + 1;
                    view.zoom_to_level(z);
                    rebuild_grid();
                    break;
                }
                case 'f':
                case 'F':
                {
                    auto z = static_cast<int>(view.zoom_level()) - 1;
                    view.zoom_to_level(z);
                    rebuild_grid();
                    break;
                }
                }
            }
        }

        void scroll_event(double /*xoffset*/, double yoffset) override
        {
            auto factor = (yoffset > 0) ? 0.9 : 1.0 / 0.9;
            auto wx = cursor_ndc_x * 2.0 * view.half_extent_y + view.center_x;
            auto wy = cursor_ndc_y * 2.0 * view.half_extent_y + view.center_y;
            view.zoom_at(factor, wx, wy);
            rebuild_grid();
        }

        void set_viewport(int width, int height)
        {
            if(height == 0)
            {
                return;
            }
            auto fwidth = static_cast<float>(width);
            auto fheight = static_cast<float>(height);
            viewport_vec = glm::vec4(0.0F, 0.0F, fwidth, fheight);
            normalized_viewport_width = fwidth / fheight;
            projection_matrix = glm::orthoLH_ZO(-normalized_viewport_width * 0.5F, normalized_viewport_width * 0.5F,
                                                -0.5F, 0.5F, -1.0F, 1.0F);

            view.viewport_width = width;
            view.viewport_height = height;
            rebuild_grid();
        }

        void framebuffer_size_event(int width, int height) override
        {
            set_viewport(width, height);
        }
    };

    map_widget::map_widget(sdl::device& dev, const char* tile_path, const char* db_path, const ini_config& ini,
                           ephemeral_data& eph, int viewport_width, int viewport_height)
        : pimpl(std::make_shared<impl>(dev, tile_path, db_path, ini, eph, viewport_width, viewport_height))
    {
    }

    map_widget::~map_widget() = default;

    void map_widget::set_visibility(const layer_visibility& vis)
    {
        pimpl->show_tiles = vis[layer_basemap];
        pimpl->vis = vis;
        pimpl->features.set_visibility(vis);
        pimpl->needs_update = true;
        // Kick a requery in case the altitude filter invalidated the cache —
        // otherwise nothing re-runs until the next input event.
    }

    void map_widget::focus_on_hit(const search_hit& hit)
    {
        auto bbox = pimpl->pick_db.get_hit_bbox(hit);
        if(!bbox)
        {
            return;
        }

        auto& d = *pimpl;
        auto cx = (bbox->lon_min + bbox->lon_max) * 0.5;
        auto cy = (bbox->lat_min + bbox->lat_max) * 0.5;
        d.view.center_x = lon_to_mx(cx);
        d.view.center_y = lat_to_my(cy);

        // Degenerate bbox (point entity) → use a fixed close-in zoom level so
        // the feature is guaranteed visible under chart_style's per-type
        // min_zoom thresholds (navaids appear by ~z9, airports by ~z7, fixes
        // by ~z10 — zoom 12 covers all of them comfortably).
        constexpr auto POINT_FOCUS_ZOOM = 12;
        auto is_point = (bbox->lon_min == bbox->lon_max && bbox->lat_min == bbox->lat_max);
        if(is_point)
        {
            d.view.zoom_to_level(POINT_FOCUS_ZOOM);
        }
        else
        {
            // Fit the bbox with 20% padding. Use the larger of the required
            // vertical / horizontal extents (the latter scaled by aspect ratio).
            auto half_height_m = (lat_to_my(bbox->lat_max) - lat_to_my(bbox->lat_min)) * 0.5;
            auto half_width_m = (lon_to_mx(bbox->lon_max) - lon_to_mx(bbox->lon_min)) * 0.5;
            auto needed = std::max(half_height_m, half_width_m / d.view.aspect_ratio());
            d.view.half_extent_y = needed * 1.2;
            // Force clamp by setting same extent through zoom(1.0).
            d.view.zoom(1.0);
        }

        d.needs_update = true;
    }

    void map_widget::set_imgui_wants_mouse(bool wants)
    {
        pimpl->imgui_wants_mouse = wants;
    }

    void map_widget::set_imgui_wants_keyboard(bool wants)
    {
        pimpl->imgui_wants_keyboard = wants;
    }

    double map_widget::zoom_level() const
    {
        return pimpl->view.zoom_level();
    }

    const std::vector<std::unique_ptr<feature_type>>& map_widget::feature_types() const
    {
        return pimpl->feature_types;
    }

    bool map_widget::draw_imgui()
    {
        auto need_more = pimpl->draw_popups();

        if(const auto* r = pimpl->active_route(); r && pimpl->route_drag.mode != impl::route_drag_mode::none)
        {
            auto is_segment = pimpl->route_drag.mode == impl::route_drag_mode::segment;
            draw_route_drag_rubber_band(pimpl->view, *r, is_segment, pimpl->route_drag.index);
        }

        return need_more;
    }

    std::shared_ptr<sdl::event_listener> map_widget::event_listener()
    {
        return pimpl;
    }

    bool map_widget::update()
    {
        // Drain phase: pull async results that arrived since the
        // previous call.
        if(pimpl->tiles)
        {
            pimpl->tiles->drain();
        }

        // Pick up fresh data from any ephemeral source whose
        // last_updated advanced. Invalidating the feature build
        // forces the submit phase below to re-issue a build request
        // even if the visible bbox hasn't changed.
        if(pimpl->eph.poll_advance())
        {
            pimpl->features.invalidate();
            pimpl->needs_update = true;
        }

        auto new_candidates = pimpl->features.drain();
        if(new_candidates)
        {
            pimpl->labels.set_candidates(pimpl->features.labels());
        }

        // Reproject labels only when the view changed or new candidates arrived.
        if(pimpl->needs_update || new_candidates)
        {
            pimpl->labels.update_positions(pimpl->view.center_x, pimpl->view.center_y, pimpl->view.half_extent_y,
                                           pimpl->view.viewport_width, pimpl->view.viewport_height, pimpl->vis);
        }

        auto result = pimpl->needs_update || (pimpl->tiles && pimpl->tiles->needs_upload()) ||
                      pimpl->features.needs_upload() || pimpl->labels.needs_upload();

        if(result)
        {
            pimpl->needs_update = false;
        }

        // Submit phase: hand any pending tile / feature build
        // requests to the worker threads so their results are ready
        // by a future frame.
        pimpl->update_tiles();

        return result;
    }

    std::vector<search_hit> map_widget::search(const std::string& query, int limit)
    {
        return pimpl->pick_db.search(query, limit);
    }

    void map_widget::add_route(flight_route route)
    {
        pimpl->routes.push_back(std::move(route));
        pimpl->features.set_routes(pimpl->routes, pimpl->active_route_index, pimpl->selected_route_index);
        pimpl->needs_update = true;
    }

    void map_widget::fit_view_to_route(std::size_t index)
    {
        assert(index < pimpl->routes.size());
        const auto& wps = pimpl->routes[index].waypoints;
        if(wps.empty())
        {
            return;
        }

        auto lat_min = waypoint_lat(wps[0]);
        auto lat_max = lat_min;
        auto lon_min = waypoint_lon(wps[0]);
        auto lon_max = lon_min;
        for(const auto& wp : wps)
        {
            auto la = waypoint_lat(wp);
            auto lo = waypoint_lon(wp);
            lat_min = std::min(la, lat_min);
            lat_max = std::max(la, lat_max);
            lon_min = std::min(lo, lon_min);
            lon_max = std::max(lo, lon_max);
        }

        auto& d = *pimpl;
        d.view.center_x = lon_to_mx((lon_min + lon_max) * 0.5);
        d.view.center_y = lat_to_my((lat_min + lat_max) * 0.5);

        auto is_point = (lon_min == lon_max && lat_min == lat_max);
        if(is_point)
        {
            constexpr auto POINT_FOCUS_ZOOM = 12;
            d.view.zoom_to_level(POINT_FOCUS_ZOOM);
        }
        else
        {
            auto half_height_m = (lat_to_my(lat_max) - lat_to_my(lat_min)) * 0.5;
            auto half_width_m = (lon_to_mx(lon_max) - lon_to_mx(lon_min)) * 0.5;
            auto needed = std::max(half_height_m, half_width_m / d.view.aspect_ratio());
            d.view.half_extent_y = needed * 1.2;
            d.view.zoom(1.0);
        }
        pimpl->rebuild_grid();
        pimpl->needs_update = true;
    }

    void map_widget::select_route(std::optional<std::size_t> index)
    {
        pimpl->select_route(index);
    }

    void map_widget::replace_route(std::size_t index, flight_route route)
    {
        assert(index < pimpl->routes.size());
        pimpl->routes[index] = std::move(route);
        pimpl->features.set_routes(pimpl->routes, pimpl->active_route_index, pimpl->selected_route_index);
        pimpl->needs_update = true;
    }

    void map_widget::remove_route(std::size_t index)
    {
        pimpl->erase_route_at(index);
    }

    void map_widget::clear_routes()
    {
        if(pimpl->routes.empty())
        {
            return;
        }
        pimpl->popups.close_route();
        pimpl->routes.clear();
        pimpl->active_route_index.reset();
        pimpl->selected_route_index.reset();
        pimpl->features.set_routes(pimpl->routes, pimpl->active_route_index, pimpl->selected_route_index);
        pimpl->route_dirty = true;
        pimpl->needs_update = true;
    }

    void map_widget::set_active_route(std::optional<std::size_t> index)
    {
        assert(!index || *index < pimpl->routes.size());
        if(pimpl->active_route_index == index)
        {
            return;
        }
        pimpl->active_route_index = index;
        pimpl->features.set_routes(pimpl->routes, pimpl->active_route_index, pimpl->selected_route_index);
        pimpl->needs_update = true;
    }

    const std::vector<flight_route>& map_widget::routes() const
    {
        return pimpl->routes;
    }

    std::optional<std::size_t> map_widget::active_route_index() const
    {
        return pimpl->active_route_index;
    }

    bool map_widget::drain_route_dirty()
    {
        auto r = pimpl->route_dirty;
        pimpl->route_dirty = false;
        return r;
    }

    std::optional<std::size_t> map_widget::drain_route_delete_request()
    {
        auto r = pimpl->route_delete_request;
        pimpl->route_delete_request.reset();
        return r;
    }

    std::optional<std::size_t> map_widget::drain_route_activate_request()
    {
        auto r = pimpl->route_activate_request;
        pimpl->route_activate_request.reset();
        return r;
    }

    void map_widget::render_frame(sdl::command_buffer& cmd, sdl::texture& swapchain)
    {
        auto& d = *pimpl;
        auto& ctx = d.render_ctx;
        ctx.projection_matrix = d.projection_matrix;
        ctx.normalized_viewport_width = d.normalized_viewport_width;

        auto s = static_cast<float>(1.0 / (2.0 * d.view.half_extent_y));
        auto cx = static_cast<float>(d.view.center_x);
        auto cy = static_cast<float>(d.view.center_y);
        auto view_matrix = glm::scale(glm::mat4(1.0F), glm::vec3(s, s, 1.0F)) *
                           glm::translate(glm::mat4(1.0F), glm::vec3(-cx, -cy, 0.0F));

        // Copy phase: upload pending vertex/texture data to GPU
        {
            sdl::copy_pass copy(cmd);
            if(!d.grid_vertices.empty())
            {
                d.grid_buffer.reset();
                auto buf = copy.create_and_upload_buffer(d.dev, sdl::buffer_usage::vertex, d.grid_vertices);
                d.grid_buffer = std::make_unique<sdl::buffer>(std::move(buf));
            }
            if(d.tiles)
            {
                d.tiles->copy(copy);
            }
            d.features.copy(copy);
            d.labels.copy(copy, d.dev);
        }

        // Render phase: one render pass with 5 pipeline stages
        sdl::render_pass pass(cmd, swapchain, 0.1F, 0.1F, 0.12F, 1.0F);

        // Textured triangles (tile basemap)
        pass.bind_pipeline(d.textured_pipeline);
        ctx.current_pass = render_pass_id::textured_trianglelist_0;
        if(d.show_tiles && d.tiles)
        {
            d.tiles->render(pass, ctx, view_matrix);
        }

        // Polygon fills (airspace/SUA selection highlights)
        pass.bind_pipeline(d.trianglelist_pipeline);
        ctx.current_pass = render_pass_id::polygon_fill_0;
        d.features.render(pass, ctx, view_matrix);

        // Lines (grid overlay)
        pass.bind_pipeline(d.linelist_pipeline);
        ctx.current_pass = render_pass_id::trianglelist_0;
        if(d.grid_buffer && d.grid_buffer->count() > 0)
        {
            sdl::uniform_buffer uniforms;
            uniforms.projection_matrix = ctx.projection_matrix;
            pass.push_vertex_uniforms(0, &uniforms, sizeof(uniforms));
            pass.push_fragment_uniforms(0, &uniforms, sizeof(uniforms));
            pass.bind_vertex_buffer(*d.grid_buffer);
            pass.draw(d.grid_buffer->count());
        }

        // SDF lines (feature polylines)
        pass.bind_pipeline(d.line_sdf_pipeline);
        ctx.current_pass = render_pass_id::line_sdf_0;
        d.features.render(pass, ctx, view_matrix);

        // Text labels (reuse textured pipeline)
        pass.bind_pipeline(d.textured_pipeline);
        ctx.current_pass = render_pass_id::text_labels_0;
        d.labels.render(pass, ctx, d.view.viewport_width, d.view.viewport_height);
    }

}
